/*
 * Decompiled with CFR 0.152.
 */
package l2.gameserver.network.l2.components;

import java.util.NoSuchElementException;

public final class NpcString
extends Enum<NpcString> {
    public static final /* enum */ NpcString NONE = new NpcString(-1);
    public static final /* enum */ NpcString THE_RADIO_SIGNAL_DETECTOR_IS_RESPONDING_A_SUSPICIOUS_PILE_OF_STONES_CATCHES_YOUR_EYE = new NpcString(11453);
    public static final /* enum */ NpcString ATT__ATTACK__S1__RO__ROGUE__S2 = new NpcString(46350);
    public static final /* enum */ NpcString LISTEN_YOU_VILLAGERS_OUR_LIEGE_WHO_WILL_SOON_BECAME_A_LORD_HAS_DEFEATED_THE_HEADLESS_KNIGHT = new NpcString(70854);
    public static final /* enum */ NpcString S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_GLUDIO = new NpcString(70859);
    public static final /* enum */ NpcString S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_DION = new NpcString(70959);
    public static final /* enum */ NpcString S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_GIRAN = new NpcString(71059);
    public static final /* enum */ NpcString S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_OREN = new NpcString(71259);
    public static final /* enum */ NpcString S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_ADEN = new NpcString(71351);
    public static final /* enum */ NpcString S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_SCHUTTGART = new NpcString(71459);
    public static final /* enum */ NpcString S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_INNADRIL = new NpcString(71159);
    public static final /* enum */ NpcString S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_RUNE = new NpcString(71659);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_GLUDIO = new NpcString(72951);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_DION = new NpcString(72952);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_GIRAN = new NpcString(72953);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_OREN = new NpcString(72954);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_ADEN = new NpcString(72955);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_INNADRIL = new NpcString(72956);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_GODDARD = new NpcString(72957);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_RUNE = new NpcString(72958);
    public static final /* enum */ NpcString PROTECT_THE_CATAPULT_OF_SCHUTTGART = new NpcString(72959);
    public static final /* enum */ NpcString THE_CATAPULT_OF_GLUDIO_HAS_BEEN_DESTROYED = new NpcString(72961);
    public static final /* enum */ NpcString THE_CATAPULT_OF_DION_HAS_BEEN_DESTROYED = new NpcString(72962);
    public static final /* enum */ NpcString THE_CATAPULT_OF_GIRAN_HAS_BEEN_DESTROYED = new NpcString(72963);
    public static final /* enum */ NpcString THE_CATAPULT_OF_OREN_HAS_BEEN_DESTROYED = new NpcString(72964);
    public static final /* enum */ NpcString THE_CATAPULT_OF_ADEN_HAS_BEEN_DESTROYED = new NpcString(72965);
    public static final /* enum */ NpcString THE_CATAPULT_OF_INNADRIL_HAS_BEEN_DESTROYED = new NpcString(72966);
    public static final /* enum */ NpcString THE_CATAPULT_OF_GODDARD_HAS_BEEN_DESTROYED = new NpcString(72967);
    public static final /* enum */ NpcString THE_CATAPULT_OF_RUNE_HAS_BEEN_DESTROYED = new NpcString(72968);
    public static final /* enum */ NpcString THE_CATAPULT_OF_SCHUTTGART_HAS_BEEN_DESTROYED = new NpcString(72969);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_GLUDIO = new NpcString(73051);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_DION = new NpcString(73052);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_GIRAN = new NpcString(73053);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_OREN = new NpcString(73054);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_ADEN = new NpcString(73055);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_INNADRIL = new NpcString(73056);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_GODDARD = new NpcString(73057);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_RUNE = new NpcString(73058);
    public static final /* enum */ NpcString PROTECT_THE_SUPPLIES_SAFE_OF_SCHUTTGART = new NpcString(73059);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_GLUDIO_HAS_BEEN_DESTROYED = new NpcString(73061);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_DION_HAS_BEEN_DESTROYED = new NpcString(73062);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_GIRAN_HAS_BEEN_DESTROYED = new NpcString(73063);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_OREN_HAS_BEEN_DESTROYED = new NpcString(73064);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_ADEN_HAS_BEEN_DESTROYED = new NpcString(73065);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_INNADRIL_HAS_BEEN_DESTROYED = new NpcString(73066);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_GODDARD_HAS_BEEN_DESTROYED = new NpcString(73067);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_RUNE_HAS_BEEN_DESTROYED = new NpcString(73068);
    public static final /* enum */ NpcString THE_SUPPLIES_SAFE_OF_SCHUTTGART_HAS_BEEN_DESTROYED = new NpcString(73069);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GLUDIO = new NpcString(73151);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_DION = new NpcString(73152);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GIRAN = new NpcString(73153);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_OREN = new NpcString(73154);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_ADEN = new NpcString(73155);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_INNADRIL = new NpcString(73156);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GODDARD = new NpcString(73157);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_RUNE = new NpcString(73158);
    public static final /* enum */ NpcString PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_SCHUTTGART = new NpcString(73159);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD = new NpcString(73161);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_DION_IS_DEAD = new NpcString(73162);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD = new NpcString(73163);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_OREN_IS_DEAD = new NpcString(73164);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD = new NpcString(73165);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD = new NpcString(73166);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD = new NpcString(73167);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD = new NpcString(73168);
    public static final /* enum */ NpcString THE_MILITARY_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD = new NpcString(73169);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GLUDIO = new NpcString(73251);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_DION = new NpcString(73252);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GIRAN = new NpcString(73253);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_OREN = new NpcString(73254);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_ADEN = new NpcString(73255);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_INNADRIL = new NpcString(73256);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GODDARD = new NpcString(73257);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_RUNE = new NpcString(73258);
    public static final /* enum */ NpcString PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_SCHUTTGART = new NpcString(73259);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD = new NpcString(73261);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_DION_IS_DEAD = new NpcString(73262);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD = new NpcString(73263);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_OREN_IS_DEAD = new NpcString(73264);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD = new NpcString(73265);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD = new NpcString(73266);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD = new NpcString(73267);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD = new NpcString(73268);
    public static final /* enum */ NpcString THE_RELIGIOUS_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD = new NpcString(73269);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GLUDIO = new NpcString(73351);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_DION = new NpcString(73352);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GIRAN = new NpcString(73353);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_OREN = new NpcString(73354);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_ADEN = new NpcString(73355);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_INNADRIL = new NpcString(73356);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GODDARD = new NpcString(73357);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_RUNE = new NpcString(73358);
    public static final /* enum */ NpcString PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_SCHUTTGART = new NpcString(73359);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD = new NpcString(73361);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_DION_IS_DEAD = new NpcString(73362);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD = new NpcString(73363);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_OREN_IS_DEAD = new NpcString(73364);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD = new NpcString(73365);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD = new NpcString(73366);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD = new NpcString(73367);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD = new NpcString(73368);
    public static final /* enum */ NpcString THE_ECONOMIC_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD = new NpcString(73369);
    public static final /* enum */ NpcString DEFEAT_S1_ENEMY_KNIGHTS = new NpcString(73451);
    public static final /* enum */ NpcString YOU_HAVE_DEFEATED_S2_OF_S1_KNIGHTS = new NpcString(73461);
    public static final /* enum */ NpcString YOU_WEAKENED_THE_ENEMYS_DEFENSE = new NpcString(73462);
    public static final /* enum */ NpcString DEFEAT_S1_WARRIORS_AND_ROGUES = new NpcString(73551);
    public static final /* enum */ NpcString YOU_HAVE_DEFEATED_S2_OF_S1_WARRIORS_AND_ROGUES = new NpcString(73561);
    public static final /* enum */ NpcString YOU_WEAKENED_THE_ENEMYS_ATTACK = new NpcString(73562);
    public static final /* enum */ NpcString DEFEAT_S1_WIZARDS_AND_SUMMONERS = new NpcString(73651);
    public static final /* enum */ NpcString YOU_HAVE_DEFEATED_S2_OF_S1_ENEMIES = new NpcString(73661);
    public static final /* enum */ NpcString YOU_WEAKENED_THE_ENEMYS_MAGIC = new NpcString(73662);
    public static final /* enum */ NpcString DEFEAT_S1_HEALERS_AND_BUFFERS = new NpcString(73751);
    public static final /* enum */ NpcString YOU_HAVE_DEFEATED_S2_OF_S1_HEALERS_AND_BUFFERS = new NpcString(73761);
    public static final /* enum */ NpcString YOU_HAVE_WEAKENED_THE_ENEMYS_SUPPORT = new NpcString(73762);
    public static final /* enum */ NpcString DEFEAT_S1_WARSMITHS_AND_OVERLORDS = new NpcString(73851);
    public static final /* enum */ NpcString YOU_HAVE_DEFEATED_S2_OF_S1_WARSMITHS_AND_OVERLORDS = new NpcString(73861);
    public static final /* enum */ NpcString YOU_DESTROYED_THE_ENEMYS_PROFESSIONALS = new NpcString(73862);
    public static final /* enum */ NpcString RETURN = new NpcString(1000170);
    public static final /* enum */ NpcString EVENT_NUMBER = new NpcString(1000172);
    public static final /* enum */ NpcString FIRST_PRIZE = new NpcString(1000173);
    public static final /* enum */ NpcString SECOND_PRIZE = new NpcString(1000174);
    public static final /* enum */ NpcString THIRD_PRIZE = new NpcString(1000175);
    public static final /* enum */ NpcString FOURTH_PRIZE = new NpcString(1000176);
    public static final /* enum */ NpcString THERE_HAS_BEEN_NO_WINNING_LOTTERY_TICKET = new NpcString(1000177);
    public static final /* enum */ NpcString YOUR_LUCKY_NUMBERS_HAVE_BEEN_SELECTED_ABOVE = new NpcString(1000179);
    public static final /* enum */ NpcString PREPARE_TO_DIE_FOREIGN_INVADERS_I_AM_GUSTAV_THE_ETERNAL_RULER_OF_THIS_FORTRESS_AND_I_HAVE_TAKEN_UP_MY_SWORD_TO_REPEL_THEE = new NpcString(1000275);
    public static final /* enum */ NpcString GLORY_TO_ADEN_THE_KINGDOM_OF_THE_LION_GLORY_TO_SIR_GUSTAV_OUR_IMMORTAL_LORD = new NpcString(1000276);
    public static final /* enum */ NpcString SOLDIERS_OF_GUSTAV_GO_FORTH_AND_DESTROY_THE_INVADERS = new NpcString(1000277);
    public static final /* enum */ NpcString THIS_IS_UNBELIEVABLE_HAVE_I_REALLY_BEEN_DEFEATED_I_SHALL_RETURN_AND_TAKE_YOUR_HEAD = new NpcString(1000278);
    public static final /* enum */ NpcString COULD_IT_BE_THAT_I_HAVE_REACHED_MY_END_I_CANNOT_DIE_WITHOUT_HONOR_WITHOUT_THE_PERMISSION_OF_SIR_GUSTAV = new NpcString(1000279);
    public static final /* enum */ NpcString AH_THE_BITTER_TASTE_OF_DEFEAT_I_FEAR_MY_TORMENTS_ARE_NOT_OVER = new NpcString(1000280);
    public static final /* enum */ NpcString THIS_WORLD_WILL_SOON_BE_ANNIHILATED = new NpcString(1000303);
    public static final /* enum */ NpcString ALL_IS_LOST__PREPARE_TO_MEET_THE_GODDESS_OF_DEATH = new NpcString(1000415);
    public static final /* enum */ NpcString ALL_IS_LOST__THE_PROPHECY_OF_DESTRUCTION_HAS_BEEN_FULFILLED = new NpcString(1000416);
    public static final /* enum */ NpcString THE_END_OF_TIME_HAS_COME__THE_PROPHECY_OF_DESTRUCTION_HAS_BEEN_FULFILLED = new NpcString(1000417);
    public static final /* enum */ NpcString THE_DAY_OF_JUDGMENT_IS_NEAR = new NpcString(1000305);
    public static final /* enum */ NpcString THE_PROPHECY_OF_DARKNESS_HAS_BEEN_FULFILLED = new NpcString(1000421);
    public static final /* enum */ NpcString AS_FORETOLD_IN_THE_PROPHECY_OF_DARKNESS__THE_ERA_OF_CHAOS_HAS_BEGUN = new NpcString(1000422);
    public static final /* enum */ NpcString THE_PROPHECY_OF_DARKNESS_HAS_COME_TO_PASS = new NpcString(1000423);
    public static final /* enum */ NpcString I_BESTOW_UPON_YOU_A_BLESSING = new NpcString(1000306);
    public static final /* enum */ NpcString S1__I_GIVE_YOU_THE_BLESSING_OF_PROPHECY = new NpcString(1000424);
    public static final /* enum */ NpcString HERALD_OF_THE_NEW_ERA__OPEN_YOUR_EYES = new NpcString(1000426);
    public static final /* enum */ NpcString S1__I_BESTOW_UPON_YOU_THE_AUTHORITY_OF_THE_ABYSS = new NpcString(1000425);
    public static final /* enum */ NpcString YOU_DONT_HAVE_ANY_HOPE__YOUR_END_HAS_COME = new NpcString(1000420);
    public static final /* enum */ NpcString A_CURSE_UPON_YOU = new NpcString(1000304);
    public static final /* enum */ NpcString S1__YOU_BRING_AN_ILL_WIND = new NpcString(1000418);
    public static final /* enum */ NpcString S1__YOU_MIGHT_AS_WELL_GIVE_UP = new NpcString(1000419);
    public static final /* enum */ NpcString THE_DEFENDERS_OF_S1_CASTLE_WILL_BE_TELEPORTED_TO_THE_INNER_CASTLE = new NpcString(1000443);
    public static final /* enum */ NpcString COMPETITION = new NpcString(1000507);
    public static final /* enum */ NpcString SEAL_VALIDATION = new NpcString(1000508);
    public static final /* enum */ NpcString PREPARATION = new NpcString(1000509);
    public static final /* enum */ NpcString DUSK = new NpcString(1000510);
    public static final /* enum */ NpcString DAWN = new NpcString(1000511);
    public static final /* enum */ NpcString NO_OWNER = new NpcString(1000512);
    public static final /* enum */ NpcString __UNREGISTERED__ = new NpcString(1000495);
    public static final /* enum */ NpcString VALAKAS_ARROGAANT_FOOL_YOU_DARE_TO_CHALLENGE_ME = new NpcString(1000519);
    public static final /* enum */ NpcString VALAKAS_FINDS_YOU_ATTACKS_ANNOYING_SILENCE = new NpcString(1801071);
    public static final /* enum */ NpcString VALAKAS_PDEF_ISM_DECREACED_SLICED_DASH = new NpcString(1801072);
    public static final /* enum */ NpcString VALAKAS_OVERWHELMED_BY_ATTACK_NOW_TIME_ATTACK = new NpcString(0x1B7B71);
    public static final /* enum */ NpcString VALAKAS_RANGED_ATTACKS_PROVOKED = new NpcString(1801074);
    public static final /* enum */ NpcString VALAKAS_HEIGHTENED_BY_COUNTERATTACKS = new NpcString(1801075);
    public static final /* enum */ NpcString VALAKAS_RANGED_ATTACKS_ENRAGED_TARGET_FREE = new NpcString(1801076);
    public static final /* enum */ NpcString VALAKAS_THE_EVIL_FIRE_DRAGON_VALAKAS_DEFEATED = new NpcString(1900151);
    public static final /* enum */ NpcString ANTHARAS_YOU_CANNOT_HOPE_TO_DEFEAT_ME = new NpcString(1000520);
    public static final /* enum */ NpcString ANTHARAS_THE_EVIL_LAND_DRAGON_ANTHARAS_DEFEATED = new NpcString(1900150);
    public static final /* enum */ NpcString ANTHARAS_EARTH_ENERGY_GATHERING_LEGS = new NpcString(1900155);
    public static final /* enum */ NpcString ANTHARAS_STARTS_ABSORB_EARTH_ENERGY = new NpcString(1900156);
    public static final /* enum */ NpcString ANTHARAS_RAISES_ITS_THICK_TAIL = new NpcString(1900157);
    public static final /* enum */ NpcString ANTHARAS_YOU_ARE_OVERCOME_ = new NpcString(1900158);
    public static final /* enum */ NpcString ANTHARAS_EYES_FILLED_WITH_RAGE = new NpcString(1900159);
    public static final /* enum */ NpcString REQUIEM_OF_HATRED = new NpcString(1000522);
    public static final /* enum */ NpcString FUGUE_OF_JUBILATION = new NpcString(1000523);
    public static final /* enum */ NpcString FRENETIC_TOCCATA = new NpcString(1000524);
    public static final /* enum */ NpcString HYPNOTIC_MAZURKA = new NpcString(1000525);
    public static final /* enum */ NpcString MOURNFUL_CHORALE_PRELUDE = new NpcString(1000526);
    public static final /* enum */ NpcString RONDO_OF_SOLITUDE = new NpcString(1000527);
    public static final /* enum */ NpcString GLUDIO = new NpcString(1001001);
    public static final /* enum */ NpcString DION = new NpcString(1001002);
    public static final /* enum */ NpcString GIRAN = new NpcString(1001003);
    public static final /* enum */ NpcString OREN = new NpcString(1001004);
    public static final /* enum */ NpcString ADEN = new NpcString(1001005);
    public static final /* enum */ NpcString INNADRIL = new NpcString(1001006);
    public static final /* enum */ NpcString THE_KINGDOM_OF_ELMORE = new NpcString(1001100);
    public static final /* enum */ NpcString GODDARD = new NpcString(1001007);
    public static final /* enum */ NpcString RUNE = new NpcString(1001008);
    public static final /* enum */ NpcString SCHUTTGART = new NpcString(1001009);
    public static final /* enum */ NpcString A_BLACK_MOON_NOW_DO_YOU_UNDERSTAND_THAT_HE_HAS_OPENED_HIS_EYES = new NpcString(1010221);
    public static final /* enum */ NpcString CLOUDS_OF_BLOOD_ARE_GATHERING_SOON_IT_WILL_START_TO_RAIN_THE_RAIN_OF_CRIMSON_BLOOD = new NpcString(1010222);
    public static final /* enum */ NpcString WHILE_THE_FOOLISH_LIGHT_WAS_ASLEEP_THE_DARKNESS_WILL_AWAKEN_FIRST_UH = new NpcString(1010223);
    public static final /* enum */ NpcString IT_IS_THE_DEEPEST_DARKNESS_WITH_ITS_ARRIVAL_THE_WORLD_WILL_SOON_DIE = new NpcString(1010224);
    public static final /* enum */ NpcString DEATH_IS_JUST_A_NEW_BEGINNING_HUHU_FEAR_NOT = new NpcString(1010225);
    public static final /* enum */ NpcString AHH_BEAUTIFUL_GODDES_OF_DEATH_COVER_OVER_THE_FILTH_OF_THOS_WORLD_YOUR_DARKNESS = new NpcString(1010226);
    public static final /* enum */ NpcString THE_GODDESS_RESURRECTION_HAS_ALREADY_BEGUN_HUHU_INSIGNIFICANT_CREATURES_LIKE_YOU_CAN_DO_NOTHING = new NpcString(1010227);
    public static final /* enum */ NpcString WHO_DARES_TO_COVET_THE_THRONE_OF_OUR_CASTLE__LEAVE_IMMEDIATELY_OR_YOU_WILL_PAY_THE_PRICE_OF_YOUR_AUDACITY_WITH_YOUR_VERY_OWN_BLOOD = new NpcString(1010623);
    public static final /* enum */ NpcString HMM_THOSE_WHO_ARE_NOT_OF_THE_BLOODLINE_ARE_COMING_THIS_WAY_TO_TAKE_OVER_THE_CASTLE__HUMPH__THE_BITTER_GRUDGES_OF_THE_DEAD = new NpcString(1010624);
    public static final /* enum */ NpcString AARGH_IF_I_DIE_THEN_THE_MAGIC_FORCE_FIELD_OF_BLOOD_WILL = new NpcString(1010625);
    public static final /* enum */ NpcString ITS_NOT_OVER_YET__IT_WONT_BE__OVER__LIKE_THIS__NEVER = new NpcString(1010626);
    public static final /* enum */ NpcString OOOH_WHO_POURED_NECTAR_ON_MY_HEAD_WHILE_I_WAS_SLEEPING = new NpcString(1010627);
    public static final /* enum */ NpcString UNDECIDED = new NpcString(1010635);
    public static final /* enum */ NpcString HEH_HEH_I_SEE_THAT_THE_FEAST_HAS_BEGAN_BE_WARY_THE_CURSE_OF_THE_HELLMANN_FAMILY_HAS_POISONED_THIS_LAND = new NpcString(1010636);
    public static final /* enum */ NpcString ARISE_MY_FAITHFUL_SERVANTS_YOU_MY_PEOPLE_WHO_HAVE_INHERITED_THE_BLOOD = new NpcString(1010637);
    public static final /* enum */ NpcString GRARR_FOR_THE_NEXT_2_MINUTES_OR_SO_THE_GAME_ARENA_ARE_WILL_BE_CLEANED = new NpcString(1010639);
    public static final /* enum */ NpcString MATCH_BEGINS_IN_S1_MINUTES = new NpcString(1800080);
    public static final /* enum */ NpcString THE_MATCH_IS_AUTOMATICALLY_CANCELED_BECAUSE_YOU_ARE_TOO_FAR_FROM_THE_ADMISSION_MANAGER = new NpcString(1800081);
    public static final /* enum */ NpcString MATCH_CANCELLED = new NpcString(0x1B77BB);
    public static final /* enum */ NpcString BEGIN_STAGE_1_FREYA = new NpcString(1801086);
    public static final /* enum */ NpcString BEGIN_STAGE_2_FREYA = new NpcString(1801087);
    public static final /* enum */ NpcString BEGIN_STAGE_3_FREYA = new NpcString(1801088);
    public static final /* enum */ NpcString BEGIN_STAGE_4_FREYA = new NpcString(1801089);
    public static final /* enum */ NpcString TIME_REMAINING_UNTIL_NEXT_BATTLE = new NpcString(1801090);
    public static final /* enum */ NpcString FREYA_HAS_STARTED_TO_MOVE = new NpcString(1801097);
    public static final /* enum */ NpcString S1_OF_BALANCE = new NpcString(1801100);
    public static final /* enum */ NpcString SWIFT_S1 = new NpcString(1801101);
    public static final /* enum */ NpcString S1_OF_BLESSING = new NpcString(1801102);
    public static final /* enum */ NpcString SHARP_S1 = new NpcString(1801103);
    public static final /* enum */ NpcString USEFUL_S1 = new NpcString(1801104);
    public static final /* enum */ NpcString RECKLESS_S1 = new NpcString(1801105);
    public static final /* enum */ NpcString ALPEN_KOOKABURRA = new NpcString(1801106);
    public static final /* enum */ NpcString ALPEN_COUGAR = new NpcString(1801107);
    public static final /* enum */ NpcString ALPEN_BUFFALO = new NpcString(1801108);
    public static final /* enum */ NpcString ALPEN_GRENDEL = new NpcString(1801109);
    public static final /* enum */ NpcString WE_HAVE_BROKEN_THROUGH_THE_GATE_DESTROY_THE_ENCAMPMENT_AND_MOVE_TO_THE_COMMAND_POST = new NpcString(1300001);
    public static final /* enum */ NpcString THE_COMMAND_GATE_HAS_OPENED_CAPTURE_THE_FLAG_QUICKLY_AND_RAISE_IT_HIGH_TO_PROCLAIM_OUR_VICTORY = new NpcString(1300002);
    public static final /* enum */ NpcString THE_GODS_HAVE_FORSAKEN_US__RETREAT = new NpcString(1300003);
    public static final /* enum */ NpcString YOU_MAY_HAVE_BROKEN_OUR_ARROWS_BUT_YOU_WILL_NEVER_BREAK_OUR_WILL_ARCHERS_RETREAT = new NpcString(1300004);
    public static final /* enum */ NpcString AT_LAST_THE_MAGIC_FIELD_THAT_PROTECTS_THE_FORTRESS_HAS_WEAKENED_VOLUNTEERS_STAND_BACK = new NpcString(1300005);
    public static final /* enum */ NpcString AIIEEEE_COMMAND_CENTER_THIS_IS_GUARD_UNIT_WE_NEED_BACKUP_RIGHT_AWAY = new NpcString(1300006);
    public static final /* enum */ NpcString FORTRESS_POWER_DISABLED = new NpcString(1300007);
    public static final /* enum */ NpcString MACHINE_NO_1_POWER_OFF = new NpcString(1300009);
    public static final /* enum */ NpcString MACHINE_NO_2_POWER_OFF = new NpcString(1300010);
    public static final /* enum */ NpcString MACHINE_NO_3_POWER_OFF = new NpcString(1300011);
    public static final /* enum */ NpcString SPIRIT_OF_FIRE_UNLEASH_YOUR_POWER_BURN_THE_ENEMY = new NpcString(1300014);
    public static final /* enum */ NpcString DO_YOU_NEED_MY_POWER_YOU_SEEM_TO_BE_STRUGGLING = new NpcString(1300016);
    public static final /* enum */ NpcString DONT_THINK_THAT_ITS_GONNA_END_LIKE_THIS = new NpcString(1300018);
    public static final /* enum */ NpcString I_FEEL_SO_MUCH_GRIEF_THAT_I_CANT_EVEN_TAKE_CARE_OF_MYSELF = new NpcString(1300020);
    public static final /* enum */ NpcString INDEPENDENT_STATE = new NpcString(1300122);
    public static final /* enum */ NpcString NONPARTISAN = new NpcString(1300123);
    public static final /* enum */ NpcString CONTRACT_STATE = new NpcString(1300124);
    public static final /* enum */ NpcString FIRST_PASSWORD_HAS_BEEN_ENTERED = new NpcString(1300125);
    public static final /* enum */ NpcString SECOND_PASSWORD_HAS_BEEN_ENTERED = new NpcString(1300126);
    public static final /* enum */ NpcString PASSWORD_HAS_NOT_BEEN_ENTERED = new NpcString(1300127);
    public static final /* enum */ NpcString ATTEMPT_S1__3_IS_IN_PROGRESS = new NpcString(1300128);
    public static final /* enum */ NpcString THE_1ST_MARK_IS_CORRECT = new NpcString(1300129);
    public static final /* enum */ NpcString THE_2ND_MARK_IS_CORRECT = new NpcString(1300130);
    public static final /* enum */ NpcString THE_MARKS_HAVE_NOT_BEEN_ASSEMBLED = new NpcString(1300131);
    public static final /* enum */ NpcString OLYMPIAD_CLASSFREE_TEAM_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT = new NpcString(1300132);
    public static final /* enum */ NpcString DOMAIN_FORTRESS = new NpcString(1300133);
    public static final /* enum */ NpcString BOUNDARY_FORTRESS = new NpcString(1300134);
    public static final /* enum */ NpcString S1HOUR_S2MINUTE = new NpcString(1300135);
    public static final /* enum */ NpcString BEGIN_STAGE_1 = new NpcString(1300150);
    public static final /* enum */ NpcString BEGIN_STAGE_2 = new NpcString(1300151);
    public static final /* enum */ NpcString BEGIN_STAGE_3 = new NpcString(1300152);
    public static final /* enum */ NpcString WHAT_A_PREDICAMENT_MY_ATTEMPTS_WERE_UNSUCCESSUFUL = new NpcString(1300162);
    public static final /* enum */ NpcString COURAGE_AMBITION_PASSION_MERCENARIES_WHO_WANT_TO_REALIZE_THEIR_DREAM_OF_FIGHTING_IN_THE_TERRITORY_WAR_COME_TO_ME_FORTUNE_AND_GLORY_ARE_WAITING_FOR_YOU = new NpcString(1300163);
    public static final /* enum */ NpcString DO_YOU_WISH_TO_FIGHT_ARE_YOU_AFRAID_NO_MATTER_HOW_HARD_YOU_TRY_YOU_HAVE_NOWHERE_TO_RUN = new NpcString(1300164);
    public static final /* enum */ NpcString CHARGE_CHARGE_CHARGE = new NpcString(1300165);
    public static final /* enum */ NpcString OLYMPIAD_CLASSFREE_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT = new NpcString(1300166);
    public static final /* enum */ NpcString OLYMPIAD_CLASS_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT = new NpcString(1300167);
    public static final /* enum */ NpcString AIRSHIP_IS_SUMMONED_IS_DEPART_IN_5_MINUTES = new NpcString(1800219);
    public static final /* enum */ NpcString AIRSHIP_IS_ARRIVED_IT_WILL_DEPART_TO_ADEN_IN_1_MINUTE = new NpcString(1800220);
    public static final /* enum */ NpcString AIRSHIP_IS_DEPARTED_TO_ADEN = new NpcString(1800221);
    public static final /* enum */ NpcString AIRSHIP_IS_ARRIVED_IT_WILL_DEPART_TO_GRACIA_IN_1_MINUTE = new NpcString(1800222);
    public static final /* enum */ NpcString AIRSHIP_IS_DEPARTED_TO_GRACIA = new NpcString(1800223);
    public static final /* enum */ NpcString IN_AIR_HARBOR_ALREADY_AIRSHIP_DOCKED_PLEASE_WAIT_AND_TRY_AGAIN = new NpcString(1800224);
    public static final /* enum */ NpcString ATTACK = new NpcString(1800243);
    public static final /* enum */ NpcString DEFEND = new NpcString(1800244);
    public static final /* enum */ NpcString MAGUEN_APPEARANCE = new NpcString(1801149);
    public static final /* enum */ NpcString THERE_ARE_5_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH = new NpcString(1800203);
    public static final /* enum */ NpcString THERE_ARE_3_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH = new NpcString(1800204);
    public static final /* enum */ NpcString THERE_ARE_1_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH = new NpcString(1800205);
    public static final /* enum */ NpcString THE_MATCH_WILL_BEGIN_IN_S1_MINUTES = new NpcString(1800206);
    public static final /* enum */ NpcString THE_MATCH_WILL_BEGIN_SHORTLY = new NpcString(1800207);
    public static final /* enum */ NpcString REGISTRATION_FOR_THE_NEXT_MATCH_WILL_END_AT_S1_MINUTES_AFTER_HOUR = new NpcString(1800208);
    public static final /* enum */ NpcString EVEN_THOUGH_YOU_BRING_SOMETHING_CALLED_A_GIFT_AMONG_YOUR_HUMANS_IT_WOULD_JUST_BE_PROBLEMATIC_FOR_ME = new NpcString(1801190);
    public static final /* enum */ NpcString I_JUST_DONT_KNOW_WHAT_EXPRESSION_I_SHOULD_HAVE_IT_APPEARED_ON_ME = new NpcString(1801191);
    public static final /* enum */ NpcString THE_FEELING_OF_THANKS_IS_JUST_TOO_MUCH_DISTANT_MEMORY_FOR_ME = new NpcString(1801192);
    public static final /* enum */ NpcString BUT_I_KIND_OF_MISS_IT = new NpcString(1801193);
    public static final /* enum */ NpcString I_AM_ICE_QUEEN_FREYA = new NpcString(1801194);
    public static final /* enum */ NpcString DEAR_S1 = new NpcString(1801195);
    public static final /* enum */ NpcString RULERS_OF_THE_SEAL_I_BRING_YOU_WONDROUS_GIFTS = new NpcString(1000431);
    public static final /* enum */ NpcString RULERS_OF_THE_SEAL_I_HAVE_SOME_EXCELLENT_WEAPONS_TO_SHOW_YOU = new NpcString(1000432);
    public static final /* enum */ NpcString IVE_BEEN_SO_BUSY_LATELY_IN_ADDITION_TO_PLANNING_MY_TRIP = new NpcString(1000433);
    public static final /* enum */ NpcString IF_YOU_HAVE_ITEMS_PLEASE_GIVE_THEM_TO_ME = new NpcString(1800279);
    public static final /* enum */ NpcString MY_STOMACH_IS_EMPTY = new NpcString(1800280);
    public static final /* enum */ NpcString IM_HUNGRY_IM_HUNGRY = new NpcString(1800281);
    public static final /* enum */ NpcString IM_STILL_NOT_FULL = new NpcString(1800282);
    public static final /* enum */ NpcString IM_STILL_HUNGRY = new NpcString(1800283);
    public static final /* enum */ NpcString I_FEEL_A_LITTLE_WOOZY = new NpcString(1800284);
    public static final /* enum */ NpcString GIVE_ME_SOMETHING_TO_EAT = new NpcString(1800285);
    public static final /* enum */ NpcString NOW_ITS_TIME_TO_EAT = new NpcString(1800286);
    public static final /* enum */ NpcString I_ALSO_NEED_A_DESSERT = new NpcString(1800287);
    public static final /* enum */ NpcString IM_STILL_HUNGRY_ = new NpcString(1800288);
    public static final /* enum */ NpcString IM_FULL_NOW_I_DONT_WANT_TO_EAT_ANYMORE = new NpcString(1800289);
    public static final /* enum */ NpcString ELAPSED_TIME = new NpcString(1911119);
    public static final /* enum */ NpcString TIME_REMAINING = new NpcString(1911120);
    public static final /* enum */ NpcString I_FEEL_STRONG_MAGIC_FLOW = new NpcString(1801111);
    public static final /* enum */ NpcString I_HAVENT_EATEN_ANYTHING_IM_SO_WEAK = new NpcString(1800290);
    public static final /* enum */ NpcString WE_MUST_SEARCH_HIGH_AND_LOW_IN_EVERY_ROOM_FOR_THE_READING_DESK_THAT_CONTAINS_THE_BOOK_WE_SEEK = new NpcString(1029450);
    public static final /* enum */ NpcString REMEMBER_THE_CONTENT_OF_THE_BOOKS_THAT_YOU_FOUND = new NpcString(1029451);
    public static final /* enum */ NpcString IT_SEEMS_THAT_YOU_CANNOT_REMEMBER_TO_THE_ROOM_OF_THE_WATCHER_WHO_FOUND_THE_BOOK = new NpcString(1029452);
    public static final /* enum */ NpcString YOUR_WORK_HERE_IS_DONE_SO_RETURN_TO_THE_CENTRAL_GUARDIAN = new NpcString(1029453);
    public static final /* enum */ NpcString THE_GUARDIAN_OF_THE_SEAL_DOESNT_SEEM_TO_GET_INJURED_AT_ALL_UNTIL_THE_BARRIER_IS_DESTROYED = new NpcString(1029550);
    public static final /* enum */ NpcString THE_DEVICE_LOCATED_IN_THE_ROOM_IN_FRONT_OF_THE_GUARDIAN_OF_THE_SEAL_IS_DEFINITELY_THE_BARRIER_THAT_CONTROLS_THE_GUARDIANS_POWER = new NpcString(1029551);
    public static final /* enum */ NpcString TO_REMOVE_THE_BARRIER_YOU_MUST_FIND_THE_RELICS_THAT_FIT_THE_BARRIER_AND_ACTIVATE_THE_DEVICE = new NpcString(1029552);
    public static final /* enum */ NpcString ALL_THE_GUARDIANS_WERE_DEFEATED_AND_THE_SEAL_WAS_REMOVED = new NpcString(1029553);
    public static final /* enum */ NpcString WHAT_TOOK_SO_LONG_I_WAITED_FOR_EVER = new NpcString(1029350);
    public static final /* enum */ NpcString I_MUST_ASK_LIBRARIAN_SOPHIA_ABOUT_THE_BOOK = new NpcString(1029351);
    public static final /* enum */ NpcString THIS_LIBRARY = new NpcString(1029352);
    public static final /* enum */ NpcString AN_UNDERGROUND_LIBRARY = new NpcString(1029353);
    public static final /* enum */ NpcString THE_BOOK_THAT_WE_SEEK_IS_CERTAINLY_HERE = new NpcString(1029354);
    public static final /* enum */ NpcString YOU_FOOLISH_INVADERS_WHO_DISTURB_THE_REST_OF_SOLINA_BE_GONE_FROM_THIS_PLACE = new NpcString(1029460);
    public static final /* enum */ NpcString I_KNOW_NOT_WHAT_YOU_SEEK_BUT_THIS_TRUTH_CANNOT_BE_HANDLED_BY_MERE_HUMANS = new NpcString(1029461);
    public static final /* enum */ NpcString I_WILL_NOT_STAND_BY_AND_WATCH_YOUR_FOOLISH_ACTIONS = new NpcString(1029462);
    public static final /* enum */ NpcString COME_AND_EAT = new NpcString(1801117);
    public static final /* enum */ NpcString LOOKS_DELICIOUS = new NpcString(1801118);
    public static final /* enum */ NpcString LETS_GO_EAT = new NpcString(1801119);
    public static final /* enum */ NpcString HALL_OF_SUFFERING = new NpcString(1800240);
    public static final /* enum */ NpcString HALL_OF_EROSION = new NpcString(1800241);
    public static final /* enum */ NpcString HEART_OF_IMMORTALITY = new NpcString(1800242);
    public static final /* enum */ NpcString YOU_CAN_HEAR_THE_UNDEAD_OF_EKIMUS_RUSHING_TOWARD_YOU = new NpcString(1800263);
    public static final /* enum */ NpcString THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NIN_ORDER_TO_DRAW_OUT_THE_COWARDLY_COHEMENES_YOU_MUST_DESTROY_ALL_THE_TUMORS = new NpcString(1800274);
    public static final /* enum */ NpcString THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED = new NpcString(1800275);
    public static final /* enum */ NpcString ALL_THE_TUMORS_INSIDE_S1_HAVE_BEEN_DESTROYED_DRIVEN_INTO_A_CORNER_COHEMENES_APPEARS_CLOSE_BY = new NpcString(1800299);
    public static final /* enum */ NpcString S1S_PARTY_HAS_MOVED_TO_A_DIFFERENT_LOCATION_THROUGH_THE_CRACK_IN_THE_TUMOR = new NpcString(1800247);
    public static final /* enum */ NpcString S1S_PARTY_HAS_ENTERED_THE_CHAMBER_OF_EKIMUS_THROUGH_THE_CRACK_IN_THE_TUMOR = new NpcString(1800248);
    public static final /* enum */ NpcString EKIMUS_HAS_SENSED_ABNORMAL_ACTIVITY = new NpcString(1800249);
    public static final /* enum */ NpcString CMON_CMON_SHOW_YOUR_FACE_YOU_LITTLE_RATS_LET_ME_SEE_WHAT_THE_DOOMED_WEAKLINGS_ARE_SCHEMING = new NpcString(1800233);
    public static final /* enum */ NpcString IMPRESSIVE = new NpcString(1800234);
    public static final /* enum */ NpcString KYAHAHA_SINCE_THE_TUMOR_HAS_BEEN_RESURRECTED_I_NO_LONGER_NEED_TO_WASTE_MY_TIME_ON_YOU = new NpcString(1800235);
    public static final /* enum */ NpcString KEU = new NpcString(1800236);
    public static final /* enum */ NpcString S1_MINUTES_ARE_REMAINING = new NpcString(1010643);
    public static final /* enum */ NpcString CONGRATULATIONS_YOU_HAVE_SUCCEEDED_AT_S1_S2_THE_INSTANCE_WILL_SHORTLY_EXPIRE = new NpcString(1800245);
    public static final /* enum */ NpcString YOU_HAVE_FAILED_AT_S1_S2 = new NpcString(1800246);
    public static final /* enum */ NpcString YOU_WILL_PARTICIPATE_IN_S1_S2_SHORTLY = new NpcString(1800262);
    public static final /* enum */ NpcString I_SHALL_ACCEPT_YOUR_CHALLENGE_S1_COME_AND_DIE_IN_THE_ARMS_OF_IMMORTALITY = new NpcString(1800261);
    public static final /* enum */ NpcString THE_TUMOR_INSIDE_S1_THAT_HAS_PROVIDED_ENERGY_N_TO_EKIMUS_IS_DESTROYED = new NpcString(1800302);
    public static final /* enum */ NpcString THE_TUMOR_INSIDE_S1_HAS_BEEN_COMPLETELY_RESURRECTED_N_AND_STARTED_TO_ENERGIZE_EKIMUS_AGAIN = new NpcString(1800303);
    public static final /* enum */ NpcString WITH_ALL_CONNECTIONS_TO_THE_TUMOR_SEVERED_EKIMUS_HAS_LOST_ITS_POWER_TO_CONTROL_THE_FERAL_HOUND = new NpcString(1800269);
    public static final /* enum */ NpcString WITH_THE_CONNECTION_TO_THE_TUMOR_RESTORED_EKIMUS_HAS_REGAINED_CONTROL_OVER_THE_FERAL_HOUND = new NpcString(1800270);
    public static final /* enum */ NpcString THERE_IS_NO_PARTY_CURRENTLY_CHALLENGING_EKIMUS = new NpcString(1800229);
    public static final /* enum */ NpcString YOU_CAN_FEEL_THE_SURGING_ENERGY_OF_DEATH_FROM_THE_TUMOR = new NpcString(1800264);
    public static final /* enum */ NpcString THE_AREA_NEAR_THE_TUMOR_IS_FULL_OF_OMINOUS_ENERGY = new NpcString(1800265);
    public static final /* enum */ NpcString THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NTHE_NEARBY_UNDEAD_THAT_WERE_ATTACKING_SEED_OF_LIFE_START_LOSING_THEIR_ENERGY_AND_RUN_AWAY = new NpcString(1800300);
    public static final /* enum */ NpcString THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED_ = new NpcString(1800301);
    public static final /* enum */ NpcString THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NTHE_SPEED_THAT_EKIMUS_CALLS_OUT_HIS_PREY_HAS_SLOWED_DOWN = new NpcString(1800304);
    public static final /* enum */ NpcString THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED__ = new NpcString(1800305);
    public static final /* enum */ NpcString BRING_MORE_MORE_SOULS = new NpcString(1800306);
    public static final /* enum */ NpcString HA_HA_HA = new NpcString(7164);
    public static final /* enum */ NpcString THE_SOUL_COFFIN_HAS_AWAKENED_EKIMUS = new NpcString(1800232);
    public static final /* enum */ NpcString YUMYUM_YUMYUM = new NpcString(1800291);
    public static final /* enum */ NpcString OLYMPIAD_CLASS_FREE_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA__S1_IN_A_MOMENT = new NpcString(1300166);
    public static final /* enum */ NpcString OLYMPIAD_CLASS_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA__S1_IN_A_MOMENT = new NpcString(1300167);
    public static final /* enum */ NpcString OLYMPIAD_CLASS_FREE_TEAM_MATCH_IS_GOING_TO_BEGIN_IN_ARENA__S1_IN_A_MOMENT = new NpcString(1300132);
    private final int sp;
    private final int sq;
    private static final /* synthetic */ NpcString[] a;

    public static NpcString[] values() {
        return (NpcString[])a.clone();
    }

    public static NpcString valueOf(String string) {
        return Enum.valueOf(NpcString.class, string);
    }

    private NpcString(int n2) {
        this.sp = n2;
        this.sq = this.name().contains("S4") ? 4 : (this.name().contains("S3") ? 3 : (this.name().contains("S2") ? 2 : (this.name().contains("S1") ? 1 : 0)));
    }

    public int getId() {
        return this.sp;
    }

    public int getSize() {
        return this.sq;
    }

    public static NpcString valueOf(int n) {
        for (NpcString npcString : NpcString.values()) {
            if (npcString.getId() != n) continue;
            return npcString;
        }
        throw new NoSuchElementException("Not find NpcString by id: " + n);
    }

    private static /* synthetic */ NpcString[] a() {
        return new NpcString[]{NONE, THE_RADIO_SIGNAL_DETECTOR_IS_RESPONDING_A_SUSPICIOUS_PILE_OF_STONES_CATCHES_YOUR_EYE, ATT__ATTACK__S1__RO__ROGUE__S2, LISTEN_YOU_VILLAGERS_OUR_LIEGE_WHO_WILL_SOON_BECAME_A_LORD_HAS_DEFEATED_THE_HEADLESS_KNIGHT, S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_GLUDIO, S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_DION, S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_GIRAN, S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_OREN, S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_ADEN, S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_SCHUTTGART, S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_INNADRIL, S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_RUNE, PROTECT_THE_CATAPULT_OF_GLUDIO, PROTECT_THE_CATAPULT_OF_DION, PROTECT_THE_CATAPULT_OF_GIRAN, PROTECT_THE_CATAPULT_OF_OREN, PROTECT_THE_CATAPULT_OF_ADEN, PROTECT_THE_CATAPULT_OF_INNADRIL, PROTECT_THE_CATAPULT_OF_GODDARD, PROTECT_THE_CATAPULT_OF_RUNE, PROTECT_THE_CATAPULT_OF_SCHUTTGART, THE_CATAPULT_OF_GLUDIO_HAS_BEEN_DESTROYED, THE_CATAPULT_OF_DION_HAS_BEEN_DESTROYED, THE_CATAPULT_OF_GIRAN_HAS_BEEN_DESTROYED, THE_CATAPULT_OF_OREN_HAS_BEEN_DESTROYED, THE_CATAPULT_OF_ADEN_HAS_BEEN_DESTROYED, THE_CATAPULT_OF_INNADRIL_HAS_BEEN_DESTROYED, THE_CATAPULT_OF_GODDARD_HAS_BEEN_DESTROYED, THE_CATAPULT_OF_RUNE_HAS_BEEN_DESTROYED, THE_CATAPULT_OF_SCHUTTGART_HAS_BEEN_DESTROYED, PROTECT_THE_SUPPLIES_SAFE_OF_GLUDIO, PROTECT_THE_SUPPLIES_SAFE_OF_DION, PROTECT_THE_SUPPLIES_SAFE_OF_GIRAN, PROTECT_THE_SUPPLIES_SAFE_OF_OREN, PROTECT_THE_SUPPLIES_SAFE_OF_ADEN, PROTECT_THE_SUPPLIES_SAFE_OF_INNADRIL, PROTECT_THE_SUPPLIES_SAFE_OF_GODDARD, PROTECT_THE_SUPPLIES_SAFE_OF_RUNE, PROTECT_THE_SUPPLIES_SAFE_OF_SCHUTTGART, THE_SUPPLIES_SAFE_OF_GLUDIO_HAS_BEEN_DESTROYED, THE_SUPPLIES_SAFE_OF_DION_HAS_BEEN_DESTROYED, THE_SUPPLIES_SAFE_OF_GIRAN_HAS_BEEN_DESTROYED, THE_SUPPLIES_SAFE_OF_OREN_HAS_BEEN_DESTROYED, THE_SUPPLIES_SAFE_OF_ADEN_HAS_BEEN_DESTROYED, THE_SUPPLIES_SAFE_OF_INNADRIL_HAS_BEEN_DESTROYED, THE_SUPPLIES_SAFE_OF_GODDARD_HAS_BEEN_DESTROYED, THE_SUPPLIES_SAFE_OF_RUNE_HAS_BEEN_DESTROYED, THE_SUPPLIES_SAFE_OF_SCHUTTGART_HAS_BEEN_DESTROYED, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GLUDIO, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_DION, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GIRAN, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_OREN, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_ADEN, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_INNADRIL, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GODDARD, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_RUNE, PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_SCHUTTGART, THE_MILITARY_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD, THE_MILITARY_ASSOCIATION_LEADER_OF_DION_IS_DEAD, THE_MILITARY_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD, THE_MILITARY_ASSOCIATION_LEADER_OF_OREN_IS_DEAD, THE_MILITARY_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD, THE_MILITARY_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD, THE_MILITARY_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD, THE_MILITARY_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD, THE_MILITARY_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GLUDIO, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_DION, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GIRAN, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_OREN, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_ADEN, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_INNADRIL, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GODDARD, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_RUNE, PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_SCHUTTGART, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_DION_IS_DEAD, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_OREN_IS_DEAD, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD, THE_RELIGIOUS_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GLUDIO, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_DION, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GIRAN, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_OREN, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_ADEN, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_INNADRIL, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GODDARD, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_RUNE, PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_SCHUTTGART, THE_ECONOMIC_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD, THE_ECONOMIC_ASSOCIATION_LEADER_OF_DION_IS_DEAD, THE_ECONOMIC_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD, THE_ECONOMIC_ASSOCIATION_LEADER_OF_OREN_IS_DEAD, THE_ECONOMIC_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD, THE_ECONOMIC_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD, THE_ECONOMIC_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD, THE_ECONOMIC_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD, THE_ECONOMIC_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD, DEFEAT_S1_ENEMY_KNIGHTS, YOU_HAVE_DEFEATED_S2_OF_S1_KNIGHTS, YOU_WEAKENED_THE_ENEMYS_DEFENSE, DEFEAT_S1_WARRIORS_AND_ROGUES, YOU_HAVE_DEFEATED_S2_OF_S1_WARRIORS_AND_ROGUES, YOU_WEAKENED_THE_ENEMYS_ATTACK, DEFEAT_S1_WIZARDS_AND_SUMMONERS, YOU_HAVE_DEFEATED_S2_OF_S1_ENEMIES, YOU_WEAKENED_THE_ENEMYS_MAGIC, DEFEAT_S1_HEALERS_AND_BUFFERS, YOU_HAVE_DEFEATED_S2_OF_S1_HEALERS_AND_BUFFERS, YOU_HAVE_WEAKENED_THE_ENEMYS_SUPPORT, DEFEAT_S1_WARSMITHS_AND_OVERLORDS, YOU_HAVE_DEFEATED_S2_OF_S1_WARSMITHS_AND_OVERLORDS, YOU_DESTROYED_THE_ENEMYS_PROFESSIONALS, RETURN, EVENT_NUMBER, FIRST_PRIZE, SECOND_PRIZE, THIRD_PRIZE, FOURTH_PRIZE, THERE_HAS_BEEN_NO_WINNING_LOTTERY_TICKET, YOUR_LUCKY_NUMBERS_HAVE_BEEN_SELECTED_ABOVE, PREPARE_TO_DIE_FOREIGN_INVADERS_I_AM_GUSTAV_THE_ETERNAL_RULER_OF_THIS_FORTRESS_AND_I_HAVE_TAKEN_UP_MY_SWORD_TO_REPEL_THEE, GLORY_TO_ADEN_THE_KINGDOM_OF_THE_LION_GLORY_TO_SIR_GUSTAV_OUR_IMMORTAL_LORD, SOLDIERS_OF_GUSTAV_GO_FORTH_AND_DESTROY_THE_INVADERS, THIS_IS_UNBELIEVABLE_HAVE_I_REALLY_BEEN_DEFEATED_I_SHALL_RETURN_AND_TAKE_YOUR_HEAD, COULD_IT_BE_THAT_I_HAVE_REACHED_MY_END_I_CANNOT_DIE_WITHOUT_HONOR_WITHOUT_THE_PERMISSION_OF_SIR_GUSTAV, AH_THE_BITTER_TASTE_OF_DEFEAT_I_FEAR_MY_TORMENTS_ARE_NOT_OVER, THIS_WORLD_WILL_SOON_BE_ANNIHILATED, ALL_IS_LOST__PREPARE_TO_MEET_THE_GODDESS_OF_DEATH, ALL_IS_LOST__THE_PROPHECY_OF_DESTRUCTION_HAS_BEEN_FULFILLED, THE_END_OF_TIME_HAS_COME__THE_PROPHECY_OF_DESTRUCTION_HAS_BEEN_FULFILLED, THE_DAY_OF_JUDGMENT_IS_NEAR, THE_PROPHECY_OF_DARKNESS_HAS_BEEN_FULFILLED, AS_FORETOLD_IN_THE_PROPHECY_OF_DARKNESS__THE_ERA_OF_CHAOS_HAS_BEGUN, THE_PROPHECY_OF_DARKNESS_HAS_COME_TO_PASS, I_BESTOW_UPON_YOU_A_BLESSING, S1__I_GIVE_YOU_THE_BLESSING_OF_PROPHECY, HERALD_OF_THE_NEW_ERA__OPEN_YOUR_EYES, S1__I_BESTOW_UPON_YOU_THE_AUTHORITY_OF_THE_ABYSS, YOU_DONT_HAVE_ANY_HOPE__YOUR_END_HAS_COME, A_CURSE_UPON_YOU, S1__YOU_BRING_AN_ILL_WIND, S1__YOU_MIGHT_AS_WELL_GIVE_UP, THE_DEFENDERS_OF_S1_CASTLE_WILL_BE_TELEPORTED_TO_THE_INNER_CASTLE, COMPETITION, SEAL_VALIDATION, PREPARATION, DUSK, DAWN, NO_OWNER, __UNREGISTERED__, VALAKAS_ARROGAANT_FOOL_YOU_DARE_TO_CHALLENGE_ME, VALAKAS_FINDS_YOU_ATTACKS_ANNOYING_SILENCE, VALAKAS_PDEF_ISM_DECREACED_SLICED_DASH, VALAKAS_OVERWHELMED_BY_ATTACK_NOW_TIME_ATTACK, VALAKAS_RANGED_ATTACKS_PROVOKED, VALAKAS_HEIGHTENED_BY_COUNTERATTACKS, VALAKAS_RANGED_ATTACKS_ENRAGED_TARGET_FREE, VALAKAS_THE_EVIL_FIRE_DRAGON_VALAKAS_DEFEATED, ANTHARAS_YOU_CANNOT_HOPE_TO_DEFEAT_ME, ANTHARAS_THE_EVIL_LAND_DRAGON_ANTHARAS_DEFEATED, ANTHARAS_EARTH_ENERGY_GATHERING_LEGS, ANTHARAS_STARTS_ABSORB_EARTH_ENERGY, ANTHARAS_RAISES_ITS_THICK_TAIL, ANTHARAS_YOU_ARE_OVERCOME_, ANTHARAS_EYES_FILLED_WITH_RAGE, REQUIEM_OF_HATRED, FUGUE_OF_JUBILATION, FRENETIC_TOCCATA, HYPNOTIC_MAZURKA, MOURNFUL_CHORALE_PRELUDE, RONDO_OF_SOLITUDE, GLUDIO, DION, GIRAN, OREN, ADEN, INNADRIL, THE_KINGDOM_OF_ELMORE, GODDARD, RUNE, SCHUTTGART, A_BLACK_MOON_NOW_DO_YOU_UNDERSTAND_THAT_HE_HAS_OPENED_HIS_EYES, CLOUDS_OF_BLOOD_ARE_GATHERING_SOON_IT_WILL_START_TO_RAIN_THE_RAIN_OF_CRIMSON_BLOOD, WHILE_THE_FOOLISH_LIGHT_WAS_ASLEEP_THE_DARKNESS_WILL_AWAKEN_FIRST_UH, IT_IS_THE_DEEPEST_DARKNESS_WITH_ITS_ARRIVAL_THE_WORLD_WILL_SOON_DIE, DEATH_IS_JUST_A_NEW_BEGINNING_HUHU_FEAR_NOT, AHH_BEAUTIFUL_GODDES_OF_DEATH_COVER_OVER_THE_FILTH_OF_THOS_WORLD_YOUR_DARKNESS, THE_GODDESS_RESURRECTION_HAS_ALREADY_BEGUN_HUHU_INSIGNIFICANT_CREATURES_LIKE_YOU_CAN_DO_NOTHING, WHO_DARES_TO_COVET_THE_THRONE_OF_OUR_CASTLE__LEAVE_IMMEDIATELY_OR_YOU_WILL_PAY_THE_PRICE_OF_YOUR_AUDACITY_WITH_YOUR_VERY_OWN_BLOOD, HMM_THOSE_WHO_ARE_NOT_OF_THE_BLOODLINE_ARE_COMING_THIS_WAY_TO_TAKE_OVER_THE_CASTLE__HUMPH__THE_BITTER_GRUDGES_OF_THE_DEAD, AARGH_IF_I_DIE_THEN_THE_MAGIC_FORCE_FIELD_OF_BLOOD_WILL, ITS_NOT_OVER_YET__IT_WONT_BE__OVER__LIKE_THIS__NEVER, OOOH_WHO_POURED_NECTAR_ON_MY_HEAD_WHILE_I_WAS_SLEEPING, UNDECIDED, HEH_HEH_I_SEE_THAT_THE_FEAST_HAS_BEGAN_BE_WARY_THE_CURSE_OF_THE_HELLMANN_FAMILY_HAS_POISONED_THIS_LAND, ARISE_MY_FAITHFUL_SERVANTS_YOU_MY_PEOPLE_WHO_HAVE_INHERITED_THE_BLOOD, GRARR_FOR_THE_NEXT_2_MINUTES_OR_SO_THE_GAME_ARENA_ARE_WILL_BE_CLEANED, MATCH_BEGINS_IN_S1_MINUTES, THE_MATCH_IS_AUTOMATICALLY_CANCELED_BECAUSE_YOU_ARE_TOO_FAR_FROM_THE_ADMISSION_MANAGER, MATCH_CANCELLED, BEGIN_STAGE_1_FREYA, BEGIN_STAGE_2_FREYA, BEGIN_STAGE_3_FREYA, BEGIN_STAGE_4_FREYA, TIME_REMAINING_UNTIL_NEXT_BATTLE, FREYA_HAS_STARTED_TO_MOVE, S1_OF_BALANCE, SWIFT_S1, S1_OF_BLESSING, SHARP_S1, USEFUL_S1, RECKLESS_S1, ALPEN_KOOKABURRA, ALPEN_COUGAR, ALPEN_BUFFALO, ALPEN_GRENDEL, WE_HAVE_BROKEN_THROUGH_THE_GATE_DESTROY_THE_ENCAMPMENT_AND_MOVE_TO_THE_COMMAND_POST, THE_COMMAND_GATE_HAS_OPENED_CAPTURE_THE_FLAG_QUICKLY_AND_RAISE_IT_HIGH_TO_PROCLAIM_OUR_VICTORY, THE_GODS_HAVE_FORSAKEN_US__RETREAT, YOU_MAY_HAVE_BROKEN_OUR_ARROWS_BUT_YOU_WILL_NEVER_BREAK_OUR_WILL_ARCHERS_RETREAT, AT_LAST_THE_MAGIC_FIELD_THAT_PROTECTS_THE_FORTRESS_HAS_WEAKENED_VOLUNTEERS_STAND_BACK, AIIEEEE_COMMAND_CENTER_THIS_IS_GUARD_UNIT_WE_NEED_BACKUP_RIGHT_AWAY, FORTRESS_POWER_DISABLED, MACHINE_NO_1_POWER_OFF, MACHINE_NO_2_POWER_OFF, MACHINE_NO_3_POWER_OFF, SPIRIT_OF_FIRE_UNLEASH_YOUR_POWER_BURN_THE_ENEMY, DO_YOU_NEED_MY_POWER_YOU_SEEM_TO_BE_STRUGGLING, DONT_THINK_THAT_ITS_GONNA_END_LIKE_THIS, I_FEEL_SO_MUCH_GRIEF_THAT_I_CANT_EVEN_TAKE_CARE_OF_MYSELF, INDEPENDENT_STATE, NONPARTISAN, CONTRACT_STATE, FIRST_PASSWORD_HAS_BEEN_ENTERED, SECOND_PASSWORD_HAS_BEEN_ENTERED, PASSWORD_HAS_NOT_BEEN_ENTERED, ATTEMPT_S1__3_IS_IN_PROGRESS, THE_1ST_MARK_IS_CORRECT, THE_2ND_MARK_IS_CORRECT, THE_MARKS_HAVE_NOT_BEEN_ASSEMBLED, OLYMPIAD_CLASSFREE_TEAM_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT, DOMAIN_FORTRESS, BOUNDARY_FORTRESS, S1HOUR_S2MINUTE, BEGIN_STAGE_1, BEGIN_STAGE_2, BEGIN_STAGE_3, WHAT_A_PREDICAMENT_MY_ATTEMPTS_WERE_UNSUCCESSUFUL, COURAGE_AMBITION_PASSION_MERCENARIES_WHO_WANT_TO_REALIZE_THEIR_DREAM_OF_FIGHTING_IN_THE_TERRITORY_WAR_COME_TO_ME_FORTUNE_AND_GLORY_ARE_WAITING_FOR_YOU, DO_YOU_WISH_TO_FIGHT_ARE_YOU_AFRAID_NO_MATTER_HOW_HARD_YOU_TRY_YOU_HAVE_NOWHERE_TO_RUN, CHARGE_CHARGE_CHARGE, OLYMPIAD_CLASSFREE_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT, OLYMPIAD_CLASS_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT, AIRSHIP_IS_SUMMONED_IS_DEPART_IN_5_MINUTES, AIRSHIP_IS_ARRIVED_IT_WILL_DEPART_TO_ADEN_IN_1_MINUTE, AIRSHIP_IS_DEPARTED_TO_ADEN, AIRSHIP_IS_ARRIVED_IT_WILL_DEPART_TO_GRACIA_IN_1_MINUTE, AIRSHIP_IS_DEPARTED_TO_GRACIA, IN_AIR_HARBOR_ALREADY_AIRSHIP_DOCKED_PLEASE_WAIT_AND_TRY_AGAIN, ATTACK, DEFEND, MAGUEN_APPEARANCE, THERE_ARE_5_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH, THERE_ARE_3_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH, THERE_ARE_1_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH, THE_MATCH_WILL_BEGIN_IN_S1_MINUTES, THE_MATCH_WILL_BEGIN_SHORTLY, REGISTRATION_FOR_THE_NEXT_MATCH_WILL_END_AT_S1_MINUTES_AFTER_HOUR, EVEN_THOUGH_YOU_BRING_SOMETHING_CALLED_A_GIFT_AMONG_YOUR_HUMANS_IT_WOULD_JUST_BE_PROBLEMATIC_FOR_ME, I_JUST_DONT_KNOW_WHAT_EXPRESSION_I_SHOULD_HAVE_IT_APPEARED_ON_ME, THE_FEELING_OF_THANKS_IS_JUST_TOO_MUCH_DISTANT_MEMORY_FOR_ME, BUT_I_KIND_OF_MISS_IT, I_AM_ICE_QUEEN_FREYA, DEAR_S1, RULERS_OF_THE_SEAL_I_BRING_YOU_WONDROUS_GIFTS, RULERS_OF_THE_SEAL_I_HAVE_SOME_EXCELLENT_WEAPONS_TO_SHOW_YOU, IVE_BEEN_SO_BUSY_LATELY_IN_ADDITION_TO_PLANNING_MY_TRIP, IF_YOU_HAVE_ITEMS_PLEASE_GIVE_THEM_TO_ME, MY_STOMACH_IS_EMPTY, IM_HUNGRY_IM_HUNGRY, IM_STILL_NOT_FULL, IM_STILL_HUNGRY, I_FEEL_A_LITTLE_WOOZY, GIVE_ME_SOMETHING_TO_EAT, NOW_ITS_TIME_TO_EAT, I_ALSO_NEED_A_DESSERT, IM_STILL_HUNGRY_, IM_FULL_NOW_I_DONT_WANT_TO_EAT_ANYMORE, ELAPSED_TIME, TIME_REMAINING, I_FEEL_STRONG_MAGIC_FLOW, I_HAVENT_EATEN_ANYTHING_IM_SO_WEAK, WE_MUST_SEARCH_HIGH_AND_LOW_IN_EVERY_ROOM_FOR_THE_READING_DESK_THAT_CONTAINS_THE_BOOK_WE_SEEK, REMEMBER_THE_CONTENT_OF_THE_BOOKS_THAT_YOU_FOUND, IT_SEEMS_THAT_YOU_CANNOT_REMEMBER_TO_THE_ROOM_OF_THE_WATCHER_WHO_FOUND_THE_BOOK, YOUR_WORK_HERE_IS_DONE_SO_RETURN_TO_THE_CENTRAL_GUARDIAN, THE_GUARDIAN_OF_THE_SEAL_DOESNT_SEEM_TO_GET_INJURED_AT_ALL_UNTIL_THE_BARRIER_IS_DESTROYED, THE_DEVICE_LOCATED_IN_THE_ROOM_IN_FRONT_OF_THE_GUARDIAN_OF_THE_SEAL_IS_DEFINITELY_THE_BARRIER_THAT_CONTROLS_THE_GUARDIANS_POWER, TO_REMOVE_THE_BARRIER_YOU_MUST_FIND_THE_RELICS_THAT_FIT_THE_BARRIER_AND_ACTIVATE_THE_DEVICE, ALL_THE_GUARDIANS_WERE_DEFEATED_AND_THE_SEAL_WAS_REMOVED, WHAT_TOOK_SO_LONG_I_WAITED_FOR_EVER, I_MUST_ASK_LIBRARIAN_SOPHIA_ABOUT_THE_BOOK, THIS_LIBRARY, AN_UNDERGROUND_LIBRARY, THE_BOOK_THAT_WE_SEEK_IS_CERTAINLY_HERE, YOU_FOOLISH_INVADERS_WHO_DISTURB_THE_REST_OF_SOLINA_BE_GONE_FROM_THIS_PLACE, I_KNOW_NOT_WHAT_YOU_SEEK_BUT_THIS_TRUTH_CANNOT_BE_HANDLED_BY_MERE_HUMANS, I_WILL_NOT_STAND_BY_AND_WATCH_YOUR_FOOLISH_ACTIONS, COME_AND_EAT, LOOKS_DELICIOUS, LETS_GO_EAT, HALL_OF_SUFFERING, HALL_OF_EROSION, HEART_OF_IMMORTALITY, YOU_CAN_HEAR_THE_UNDEAD_OF_EKIMUS_RUSHING_TOWARD_YOU, THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NIN_ORDER_TO_DRAW_OUT_THE_COWARDLY_COHEMENES_YOU_MUST_DESTROY_ALL_THE_TUMORS, THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED, ALL_THE_TUMORS_INSIDE_S1_HAVE_BEEN_DESTROYED_DRIVEN_INTO_A_CORNER_COHEMENES_APPEARS_CLOSE_BY, S1S_PARTY_HAS_MOVED_TO_A_DIFFERENT_LOCATION_THROUGH_THE_CRACK_IN_THE_TUMOR, S1S_PARTY_HAS_ENTERED_THE_CHAMBER_OF_EKIMUS_THROUGH_THE_CRACK_IN_THE_TUMOR, EKIMUS_HAS_SENSED_ABNORMAL_ACTIVITY, CMON_CMON_SHOW_YOUR_FACE_YOU_LITTLE_RATS_LET_ME_SEE_WHAT_THE_DOOMED_WEAKLINGS_ARE_SCHEMING, IMPRESSIVE, KYAHAHA_SINCE_THE_TUMOR_HAS_BEEN_RESURRECTED_I_NO_LONGER_NEED_TO_WASTE_MY_TIME_ON_YOU, KEU, S1_MINUTES_ARE_REMAINING, CONGRATULATIONS_YOU_HAVE_SUCCEEDED_AT_S1_S2_THE_INSTANCE_WILL_SHORTLY_EXPIRE, YOU_HAVE_FAILED_AT_S1_S2, YOU_WILL_PARTICIPATE_IN_S1_S2_SHORTLY, I_SHALL_ACCEPT_YOUR_CHALLENGE_S1_COME_AND_DIE_IN_THE_ARMS_OF_IMMORTALITY, THE_TUMOR_INSIDE_S1_THAT_HAS_PROVIDED_ENERGY_N_TO_EKIMUS_IS_DESTROYED, THE_TUMOR_INSIDE_S1_HAS_BEEN_COMPLETELY_RESURRECTED_N_AND_STARTED_TO_ENERGIZE_EKIMUS_AGAIN, WITH_ALL_CONNECTIONS_TO_THE_TUMOR_SEVERED_EKIMUS_HAS_LOST_ITS_POWER_TO_CONTROL_THE_FERAL_HOUND, WITH_THE_CONNECTION_TO_THE_TUMOR_RESTORED_EKIMUS_HAS_REGAINED_CONTROL_OVER_THE_FERAL_HOUND, THERE_IS_NO_PARTY_CURRENTLY_CHALLENGING_EKIMUS, YOU_CAN_FEEL_THE_SURGING_ENERGY_OF_DEATH_FROM_THE_TUMOR, THE_AREA_NEAR_THE_TUMOR_IS_FULL_OF_OMINOUS_ENERGY, THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NTHE_NEARBY_UNDEAD_THAT_WERE_ATTACKING_SEED_OF_LIFE_START_LOSING_THEIR_ENERGY_AND_RUN_AWAY, THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED_, THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NTHE_SPEED_THAT_EKIMUS_CALLS_OUT_HIS_PREY_HAS_SLOWED_DOWN, THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED__, BRING_MORE_MORE_SOULS, HA_HA_HA, THE_SOUL_COFFIN_HAS_AWAKENED_EKIMUS, YUMYUM_YUMYUM, OLYMPIAD_CLASS_FREE_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA__S1_IN_A_MOMENT, OLYMPIAD_CLASS_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA__S1_IN_A_MOMENT, OLYMPIAD_CLASS_FREE_TEAM_MATCH_IS_GOING_TO_BEGIN_IN_ARENA__S1_IN_A_MOMENT};
    }

    static {
        a = NpcString.a();
    }
}
