/*
 * Decompiled with CFR 0.152.
 */
package l2.gameserver.handler.telegram;

import l2.gameserver.handler.telegram.TelegramCommandHandler;
import l2.gameserver.handler.telegram.impl.AIStatsCommand;
import l2.gameserver.handler.telegram.impl.AbortCommand;
import l2.gameserver.handler.telegram.impl.AnnounceCommand;
import l2.gameserver.handler.telegram.impl.CharBanCommand;
import l2.gameserver.handler.telegram.impl.ChatBanCommand;
import l2.gameserver.handler.telegram.impl.ConfigCommand;
import l2.gameserver.handler.telegram.impl.EffectStatsCommand;
import l2.gameserver.handler.telegram.impl.FindCharCommand;
import l2.gameserver.handler.telegram.impl.GCCommand;
import l2.gameserver.handler.telegram.impl.GiveAllByHwidCommand;
import l2.gameserver.handler.telegram.impl.GiveAllByIpCommand;
import l2.gameserver.handler.telegram.impl.GiveAllCommand;
import l2.gameserver.handler.telegram.impl.GiveItemCommand;
import l2.gameserver.handler.telegram.impl.GmListCommand;
import l2.gameserver.handler.telegram.impl.HeapCommand;
import l2.gameserver.handler.telegram.impl.HelpCommand;
import l2.gameserver.handler.telegram.impl.InventoryCommand;
import l2.gameserver.handler.telegram.impl.JailCommand;
import l2.gameserver.handler.telegram.impl.KickCommand;
import l2.gameserver.handler.telegram.impl.ListClansCommand;
import l2.gameserver.handler.telegram.impl.ListOnlinePlayersCommand;
import l2.gameserver.handler.telegram.impl.MemCommand;
import l2.gameserver.handler.telegram.impl.NetCommand;
import l2.gameserver.handler.telegram.impl.NoSpamCommand;
import l2.gameserver.handler.telegram.impl.OnlineCommand;
import l2.gameserver.handler.telegram.impl.PathfindCommand;
import l2.gameserver.handler.telegram.impl.PoolCommand;
import l2.gameserver.handler.telegram.impl.PrivateMessageCommand;
import l2.gameserver.handler.telegram.impl.RemoveItemCommand;
import l2.gameserver.handler.telegram.impl.RestartCommand;
import l2.gameserver.handler.telegram.impl.SetClassCommand;
import l2.gameserver.handler.telegram.impl.SetHeroCommand;
import l2.gameserver.handler.telegram.impl.SetLevelCommand;
import l2.gameserver.handler.telegram.impl.SetNameCommand;
import l2.gameserver.handler.telegram.impl.SetNobleCommand;
import l2.gameserver.handler.telegram.impl.SetPaCommand;
import l2.gameserver.handler.telegram.impl.SetTitleCommand;
import l2.gameserver.handler.telegram.impl.ShutdownCommand;
import l2.gameserver.handler.telegram.impl.StatusCommand;
import l2.gameserver.handler.telegram.impl.ThreadsCommand;
import l2.gameserver.handler.telegram.impl.UnjailCommand;
import l2.gameserver.handler.telegram.impl.UptimeCommand;
import l2.gameserver.handler.telegram.impl.VersionCommand;
import l2.gameserver.handler.telegram.impl.WhoisCharCommand;

public class TelegramCommandRegistry {
    public static void registerCommands() {
        TelegramCommandHandler telegramCommandHandler = TelegramCommandHandler.getInstance();
        telegramCommandHandler.registerCommandHandler(new StatusCommand());
        telegramCommandHandler.registerCommandHandler(new HelpCommand());
        telegramCommandHandler.registerCommandHandler(new OnlineCommand());
        telegramCommandHandler.registerCommandHandler(new MemCommand());
        telegramCommandHandler.registerCommandHandler(new GiveItemCommand());
        telegramCommandHandler.registerCommandHandler(new GiveAllByHwidCommand());
        telegramCommandHandler.registerCommandHandler(new GiveAllByIpCommand());
        telegramCommandHandler.registerCommandHandler(new GiveAllCommand());
        telegramCommandHandler.registerCommandHandler(new ShutdownCommand());
        telegramCommandHandler.registerCommandHandler(new AnnounceCommand());
        telegramCommandHandler.registerCommandHandler(new RestartCommand());
        telegramCommandHandler.registerCommandHandler(new PrivateMessageCommand());
        telegramCommandHandler.registerCommandHandler(new KickCommand());
        telegramCommandHandler.registerCommandHandler(new ChatBanCommand());
        telegramCommandHandler.registerCommandHandler(new CharBanCommand());
        telegramCommandHandler.registerCommandHandler(new NoSpamCommand());
        telegramCommandHandler.registerCommandHandler(new ConfigCommand());
        telegramCommandHandler.registerCommandHandler(new PoolCommand());
        telegramCommandHandler.registerCommandHandler(new ThreadsCommand());
        telegramCommandHandler.registerCommandHandler(new GCCommand());
        telegramCommandHandler.registerCommandHandler(new NetCommand());
        telegramCommandHandler.registerCommandHandler(new PathfindCommand());
        telegramCommandHandler.registerCommandHandler(new AIStatsCommand());
        telegramCommandHandler.registerCommandHandler(new EffectStatsCommand());
        telegramCommandHandler.registerCommandHandler(new HeapCommand());
        telegramCommandHandler.registerCommandHandler(new UptimeCommand());
        telegramCommandHandler.registerCommandHandler(new AbortCommand());
        telegramCommandHandler.registerCommandHandler(new VersionCommand());
        telegramCommandHandler.registerCommandHandler(new WhoisCharCommand());
        telegramCommandHandler.registerCommandHandler(new GmListCommand());
        telegramCommandHandler.registerCommandHandler(new FindCharCommand());
        telegramCommandHandler.registerCommandHandler(new InventoryCommand());
        telegramCommandHandler.registerCommandHandler(new RemoveItemCommand());
        telegramCommandHandler.registerCommandHandler(new ListClansCommand());
        telegramCommandHandler.registerCommandHandler(new SetLevelCommand());
        telegramCommandHandler.registerCommandHandler(new JailCommand());
        telegramCommandHandler.registerCommandHandler(new UnjailCommand());
        telegramCommandHandler.registerCommandHandler(new ListOnlinePlayersCommand());
        telegramCommandHandler.registerCommandHandler(new SetClassCommand());
        telegramCommandHandler.registerCommandHandler(new SetHeroCommand());
        telegramCommandHandler.registerCommandHandler(new SetNameCommand());
        telegramCommandHandler.registerCommandHandler(new SetNobleCommand());
        telegramCommandHandler.registerCommandHandler(new SetPaCommand());
        telegramCommandHandler.registerCommandHandler(new SetTitleCommand());
    }
}
