/*
 * Decompiled with CFR 0.152.
 */
package l2.gameserver.skills;

import java.util.NoSuchElementException;
import l2.gameserver.skills.AbnormalEffectType;

public final class AbnormalEffect
extends Enum<AbnormalEffect> {
    public static final /* enum */ AbnormalEffect NULL = new AbnormalEffect("null", 0);
    public static final /* enum */ AbnormalEffect DOT_BLEEDING = new AbnormalEffect("bleeding", 1);
    public static final /* enum */ AbnormalEffect DOT_POISON = new AbnormalEffect("poison", 2);
    public static final /* enum */ AbnormalEffect DOT_FIRE = new AbnormalEffect("redcircle", 3);
    public static final /* enum */ AbnormalEffect DOT_WATER = new AbnormalEffect("ice", 4);
    public static final /* enum */ AbnormalEffect DOT_WIND = new AbnormalEffect("wind", 5);
    public static final /* enum */ AbnormalEffect DOT_SOIL = new AbnormalEffect("confused", 6);
    public static final /* enum */ AbnormalEffect STUN = new AbnormalEffect("stun", 7);
    public static final /* enum */ AbnormalEffect SLEEP = new AbnormalEffect("sleep", 8);
    public static final /* enum */ AbnormalEffect SILENCE = new AbnormalEffect("muted", 9);
    public static final /* enum */ AbnormalEffect ROOT = new AbnormalEffect("root", 10);
    public static final /* enum */ AbnormalEffect PARALYZE = new AbnormalEffect("hold1", 11);
    public static final /* enum */ AbnormalEffect FLESH_STONE = new AbnormalEffect("hold2", 12);
    public static final /* enum */ AbnormalEffect DOT_MP = new AbnormalEffect("mana_burn", 13);
    public static final /* enum */ AbnormalEffect BIG_HEAD = new AbnormalEffect("bighead", 14);
    public static final /* enum */ AbnormalEffect DOT_FIRE_AREA = new AbnormalEffect("fire_burn", 15);
    public static final /* enum */ AbnormalEffect CHANGE_TEXTURE = new AbnormalEffect("change_texture", 16);
    public static final /* enum */ AbnormalEffect BIG_BODY = new AbnormalEffect("grow", 17);
    public static final /* enum */ AbnormalEffect FLOATING_ROOT = new AbnormalEffect("floatroot", 18);
    public static final /* enum */ AbnormalEffect DANCE_ROOT = new AbnormalEffect("dancestun", 19);
    public static final /* enum */ AbnormalEffect GHOST_STUN = new AbnormalEffect("firerootstun", 20);
    public static final /* enum */ AbnormalEffect STEALTH = new AbnormalEffect("shadow", 21);
    public static final /* enum */ AbnormalEffect SEIZURE1 = new AbnormalEffect("seizure1", 22);
    public static final /* enum */ AbnormalEffect SEIZURE2 = new AbnormalEffect("seizure2", 23);
    public static final /* enum */ AbnormalEffect MAGIC_SQUARE = new AbnormalEffect("magiccircle", 24);
    public static final /* enum */ AbnormalEffect FREEZING = new AbnormalEffect("ice2", 25);
    public static final /* enum */ AbnormalEffect SHAKE = new AbnormalEffect("earthquake", 26);
    public static final /* enum */ AbnormalEffect ULTIMATE_DEFENCE = new AbnormalEffect("invul1", 28);
    public static final /* enum */ AbnormalEffect VP_UP = new AbnormalEffect("vp_up", 29);
    public static final /* enum */ AbnormalEffect VP_KEEP = new AbnormalEffect("vp_keep", 29);
    public static final /* enum */ AbnormalEffect REAL_TARGET = new AbnormalEffect("realtarget", 30);
    public static final /* enum */ AbnormalEffect DEATH_MARK = new AbnormalEffect("deathmark", 31);
    public static final /* enum */ AbnormalEffect TURN_FLEE = new AbnormalEffect("soulshock", 32);
    public static final /* enum */ AbnormalEffect INVINCIBILITY = new AbnormalEffect("invul2", 33);
    public static final /* enum */ AbnormalEffect AIR_BATTLE_SLOW = new AbnormalEffect("redglow", 34);
    public static final /* enum */ AbnormalEffect AIR_BATTLE_ROOT = new AbnormalEffect("redglow2", 35);
    public static final /* enum */ AbnormalEffect CHANGE_WP = new AbnormalEffect("baguettesword", 36);
    public static final /* enum */ AbnormalEffect CHANGE_HAIR_G = new AbnormalEffect("change_hair_g", 37);
    public static final /* enum */ AbnormalEffect CHANGE_HAIR_P = new AbnormalEffect("change_hair_p", 38);
    public static final /* enum */ AbnormalEffect CHANGE_HAIR_B = new AbnormalEffect("change_hair_b", 39);
    public static final /* enum */ AbnormalEffect UNKNOWN_40 = new AbnormalEffect("unk_40", 40);
    public static final /* enum */ AbnormalEffect STIGMA_OF_SILEN = new AbnormalEffect("stigma", 41);
    public static final /* enum */ AbnormalEffect SPEED_DOWN = new AbnormalEffect("speed_down", 42);
    public static final /* enum */ AbnormalEffect FROZEN_PILLAR = new AbnormalEffect("frozenpillar", 43);
    public static final /* enum */ AbnormalEffect CHANGE_VES_S = new AbnormalEffect("vesper_red", 44);
    public static final /* enum */ AbnormalEffect CHANGE_VES_C = new AbnormalEffect("vesper_noble", 45);
    public static final /* enum */ AbnormalEffect CHANGE_VES_D = new AbnormalEffect("vesper_dark", 46);
    public static final /* enum */ AbnormalEffect TIME_BOMB = new AbnormalEffect("time_bomb", 47);
    public static final /* enum */ AbnormalEffect MP_SHIELD = new AbnormalEffect("ave_mp_shield", 48);
    public static final /* enum */ AbnormalEffect AIRBIND = new AbnormalEffect("airbird", 49);
    public static final /* enum */ AbnormalEffect CHANGEBODY = new AbnormalEffect("change_body", 50);
    public static final /* enum */ AbnormalEffect KNOCKDOWN = new AbnormalEffect("knockdown", 51);
    public static final /* enum */ AbnormalEffect NAVIT_ADVENT = new AbnormalEffect("navit_advent", 52);
    public static final /* enum */ AbnormalEffect KNOCKBACK = new AbnormalEffect("knockdown1", 53);
    public static final /* enum */ AbnormalEffect CHANGE_7ANNIVERSARY = new AbnormalEffect("anniversary", 54);
    public static final /* enum */ AbnormalEffect ON_SPOT_MOVEMENT = new AbnormalEffect("on_spot_movement", 55);
    public static final /* enum */ AbnormalEffect DEPORT = new AbnormalEffect("deport", 56);
    public static final /* enum */ AbnormalEffect AURA_BUFF = new AbnormalEffect("aura_buff", 57);
    public static final /* enum */ AbnormalEffect AURA_BUFF_SELF = new AbnormalEffect("aura_buff_self", 58);
    public static final /* enum */ AbnormalEffect AURA_DEBUFF = new AbnormalEffect("aura_debuff", 59);
    public static final /* enum */ AbnormalEffect AURA_DEBUFF_SELF = new AbnormalEffect("aura_debuff_self", 60);
    public static final /* enum */ AbnormalEffect HURRICANE = new AbnormalEffect("hurricane", 61);
    public static final /* enum */ AbnormalEffect HURRICANE_SELF = new AbnormalEffect("hurricane_self", 62);
    public static final /* enum */ AbnormalEffect BLACK_MARK = new AbnormalEffect("black_mark", 63);
    public static final /* enum */ AbnormalEffect BR_SOUL_AVATAR = new AbnormalEffect("br_soul_avatar", 64);
    public static final /* enum */ AbnormalEffect CHANGE_GRADE_B = new AbnormalEffect("change_grade_b", 65);
    public static final /* enum */ AbnormalEffect BR_BEAM_SWORD_ONEHAND = new AbnormalEffect("beam_sword_one_hand", 66);
    public static final /* enum */ AbnormalEffect BR_BEAM_SWORD_DUAL = new AbnormalEffect("beam_sword_dual", 67);
    public static final /* enum */ AbnormalEffect NO_CHAT = new AbnormalEffect("no_chat", 68);
    public static final /* enum */ AbnormalEffect HERB_PA_UP = new AbnormalEffect("herb_pa_up", 69);
    public static final /* enum */ AbnormalEffect HERB_MA_UP = new AbnormalEffect("herb_mp_up", 70);
    public static final /* enum */ AbnormalEffect SEED_TALISMAN1 = new AbnormalEffect("seed_talisman1", 71);
    public static final /* enum */ AbnormalEffect SEED_TALISMAN2 = new AbnormalEffect("seed_talisman2", 72);
    public static final /* enum */ AbnormalEffect SEED_TALISMAN3 = new AbnormalEffect("seed_talisman3", 73);
    public static final /* enum */ AbnormalEffect SEED_TALISMAN4 = new AbnormalEffect("seed_talisman4", 74);
    public static final /* enum */ AbnormalEffect SEED_TALISMAN5 = new AbnormalEffect("seed_talisman5", 75);
    public static final /* enum */ AbnormalEffect SEED_TALISMAN6 = new AbnormalEffect("seed_talisman6", 76);
    public static final /* enum */ AbnormalEffect CURIOUS_HOUSE = new AbnormalEffect("curios_house", 77);
    public static final /* enum */ AbnormalEffect NGRADE_CHANGE = new AbnormalEffect("no_grade_change", 78);
    public static final /* enum */ AbnormalEffect DGRADE_CHANGE = new AbnormalEffect("d_grade_change", 79);
    public static final /* enum */ AbnormalEffect CGRADE_CHANGE = new AbnormalEffect("c_grade_change", 80);
    public static final /* enum */ AbnormalEffect BGRADE_CHANGE = new AbnormalEffect("b_grade_change", 81);
    public static final /* enum */ AbnormalEffect AGRADE_CHANGE = new AbnormalEffect("a_grade_change", 82);
    public static final /* enum */ AbnormalEffect SWEET_ICE_FLAKES = new AbnormalEffect("sweet_ice_flakes", 83);
    public static final /* enum */ AbnormalEffect FANTASY_ICE_FLAKES = new AbnormalEffect("fantasy_ice_flakes", 84);
    public static final /* enum */ AbnormalEffect CHANGE_XMAS = new AbnormalEffect("charge_xmas", 85);
    public static final /* enum */ AbnormalEffect CARD_PC_DECO = new AbnormalEffect("card_pc_deco", 86);
    public static final /* enum */ AbnormalEffect CHANGE_DINOS = new AbnormalEffect("change_dinos", 87);
    public static final /* enum */ AbnormalEffect CHANGE_VALENTINE = new AbnormalEffect("change_valentine", 88);
    public static final /* enum */ AbnormalEffect CHOCOLATE = new AbnormalEffect("chocolate", 89);
    public static final /* enum */ AbnormalEffect CANDY = new AbnormalEffect("candy", 90);
    public static final /* enum */ AbnormalEffect COOKIE = new AbnormalEffect("cookie", 91);
    public static final /* enum */ AbnormalEffect STARS_0 = new AbnormalEffect("stars_0", 92);
    public static final /* enum */ AbnormalEffect STARS_1 = new AbnormalEffect("stars_1", 93);
    public static final /* enum */ AbnormalEffect STARS_2 = new AbnormalEffect("stars_2", 94);
    public static final /* enum */ AbnormalEffect STARS_3 = new AbnormalEffect("stars_3", 95);
    public static final /* enum */ AbnormalEffect STARS_4 = new AbnormalEffect("stars_4", 96);
    public static final /* enum */ AbnormalEffect STARS_5 = new AbnormalEffect("stars_5", 97);
    public static final /* enum */ AbnormalEffect DUELING = new AbnormalEffect("dueling", 98);
    public static final /* enum */ AbnormalEffect FREEZING2 = new AbnormalEffect("freezing2", 99);
    public static final /* enum */ AbnormalEffect CHANGE_YOGI = new AbnormalEffect("change_yogi", 100);
    public static final /* enum */ AbnormalEffect YOGI = new AbnormalEffect("yogi", 101);
    public static final /* enum */ AbnormalEffect MUSICAL_NOTE_YELLOW = new AbnormalEffect("musical_note_yellow", 102);
    public static final /* enum */ AbnormalEffect MUSICAL_NOTE_BLUE = new AbnormalEffect("musical_note_blue", 103);
    public static final /* enum */ AbnormalEffect MUSICAL_NOTE_GREEN = new AbnormalEffect("musical_note_green", 104);
    public static final /* enum */ AbnormalEffect TENTH_ANNIVERSARY = new AbnormalEffect("tenth_anniversary", 105);
    public static final /* enum */ AbnormalEffect XMAS_SOCKS = new AbnormalEffect("xmas_socks", 106);
    public static final /* enum */ AbnormalEffect XMAS_TREE = new AbnormalEffect("xmas_tree", 107);
    public static final /* enum */ AbnormalEffect XMAS_SNOWMAN = new AbnormalEffect("xmas_snowman", 108);
    public static final /* enum */ AbnormalEffect OTHELL_ROGUE_BLUFF = new AbnormalEffect("othell_rouge_buff", 109);
    public static final /* enum */ AbnormalEffect HE_PROTECT = new AbnormalEffect("he_protect", 110);
    public static final /* enum */ AbnormalEffect SU_SUMCROSS = new AbnormalEffect("su_sumcross", 111);
    public static final /* enum */ AbnormalEffect WIND_STUN = new AbnormalEffect("wind_stun", 112);
    public static final /* enum */ AbnormalEffect STORM_SIGN2 = new AbnormalEffect("storm_sign2", 113);
    public static final /* enum */ AbnormalEffect STORM_SIGN1 = new AbnormalEffect("storm_sign1", 114);
    public static final /* enum */ AbnormalEffect WIND_BLEND = new AbnormalEffect("wind_blend", 115);
    public static final /* enum */ AbnormalEffect DECEPTIVE_BLINK = new AbnormalEffect("deceptive_blink", 116);
    public static final /* enum */ AbnormalEffect WIND_HIDE = new AbnormalEffect("wind_hide", 117);
    public static final /* enum */ AbnormalEffect PSY_POWER = new AbnormalEffect("psy_power", 118);
    public static final /* enum */ AbnormalEffect SQUALL = new AbnormalEffect("squall", 119);
    public static final /* enum */ AbnormalEffect WIND_ILLUSION = new AbnormalEffect("wind_illusion", 120);
    public static final /* enum */ AbnormalEffect SAYHA_FURY = new AbnormalEffect("sayha_fury", 121);
    public static final /* enum */ AbnormalEffect HIDE4 = new AbnormalEffect("hide4", 123);
    public static final /* enum */ AbnormalEffect PMENTAL_TRAIL = new AbnormalEffect("pmental_trail", 124);
    public static final /* enum */ AbnormalEffect HOLD_LIGHTING = new AbnormalEffect("hold_lighting", 125);
    public static final /* enum */ AbnormalEffect GRAVITY_SPACE_3 = new AbnormalEffect("gravity_space_3", 126);
    public static final /* enum */ AbnormalEffect SPACEREF = new AbnormalEffect("spaceref", 127);
    public static final /* enum */ AbnormalEffect HE_ASPECT = new AbnormalEffect("he_aspect", 128);
    public static final /* enum */ AbnormalEffect RUNWAY_ARMOR1 = new AbnormalEffect("runway_armor1", 129);
    public static final /* enum */ AbnormalEffect RUNWAY_ARMOR2 = new AbnormalEffect("runway_armor2", 130);
    public static final /* enum */ AbnormalEffect RUNWAY_ARMOR3 = new AbnormalEffect("runway_armor3", 131);
    public static final /* enum */ AbnormalEffect RUNWAY_ARMOR4 = new AbnormalEffect("runway_armor4", 132);
    public static final /* enum */ AbnormalEffect RUNWAY_ARMOR5 = new AbnormalEffect("runway_armor5", 133);
    public static final /* enum */ AbnormalEffect RUNWAY_ARMOR6 = new AbnormalEffect("runway_armor6", 134);
    public static final /* enum */ AbnormalEffect RUNWAY_WEAPON1 = new AbnormalEffect("runway_weapon1", 135);
    public static final /* enum */ AbnormalEffect RUNWAY_WEAPON2 = new AbnormalEffect("runway_weapon2", 136);
    public static final /* enum */ AbnormalEffect PALADIN_PROTECTION = new AbnormalEffect("paladin_protection", 141);
    public static final /* enum */ AbnormalEffect SENTINEL_PROTECTION = new AbnormalEffect("sentinel_protection", 142);
    public static final /* enum */ AbnormalEffect REAL_TARGET_2 = new AbnormalEffect("real_target_2", 143);
    public static final /* enum */ AbnormalEffect DIVINITY = new AbnormalEffect("divinity", 144);
    public static final /* enum */ AbnormalEffect SHILLIEN_PROTECTION = new AbnormalEffect("shillien_protection", 145);
    public static final /* enum */ AbnormalEffect EVENT_STARS_0 = new AbnormalEffect("event_stars_0", 146);
    public static final /* enum */ AbnormalEffect EVENT_STARS_1 = new AbnormalEffect("event_stars_1", 147);
    public static final /* enum */ AbnormalEffect EVENT_STARS_2 = new AbnormalEffect("event_stars_2", 148);
    public static final /* enum */ AbnormalEffect EVENT_STARS_3 = new AbnormalEffect("event_stars_3", 149);
    public static final /* enum */ AbnormalEffect EVENT_STARS_4 = new AbnormalEffect("event_stars_4", 150);
    public static final /* enum */ AbnormalEffect EVENT_STARS_5 = new AbnormalEffect("event_stars_5", 151);
    public static final /* enum */ AbnormalEffect ABSORB_SHIELD = new AbnormalEffect("absorb_shield", 152);
    public static final /* enum */ AbnormalEffect PHOENIX_AURA = new AbnormalEffect("phoenix_aura", 153);
    public static final /* enum */ AbnormalEffect REVENGE_AURA = new AbnormalEffect("revenge_aura", 154);
    public static final /* enum */ AbnormalEffect EVAS_AURA = new AbnormalEffect("evas_aura", 155);
    public static final /* enum */ AbnormalEffect TEMPLAR_AURA = new AbnormalEffect("templar_aura", 156);
    public static final /* enum */ AbnormalEffect LONG_BLOW = new AbnormalEffect("long_blow", 157);
    public static final /* enum */ AbnormalEffect WIDE_SWORD = new AbnormalEffect("wide_sword", 158);
    public static final /* enum */ AbnormalEffect BIG_FIST = new AbnormalEffect("big_fist", 159);
    public static final /* enum */ AbnormalEffect SHADOW_STEP = new AbnormalEffect("shadow_step", 160);
    public static final /* enum */ AbnormalEffect TORNADO = new AbnormalEffect("tornado", 161);
    public static final /* enum */ AbnormalEffect SNOW_SLOW = new AbnormalEffect("snow_slow", 162);
    public static final /* enum */ AbnormalEffect SNOW_HOLD = new AbnormalEffect("snow_hold", 163);
    public static final /* enum */ AbnormalEffect UNK_164 = new AbnormalEffect("unk_164", 164);
    public static final /* enum */ AbnormalEffect TORNADO_SLOW = new AbnormalEffect("tornado_slow", 165);
    public static final /* enum */ AbnormalEffect ASTATINE_WATER = new AbnormalEffect("astatine_water", 166);
    public static final /* enum */ AbnormalEffect BIG_BODY_COMBINATION_CAT_NPC = new AbnormalEffect("big_body_combination_cat_npc", 167);
    public static final /* enum */ AbnormalEffect BIG_BODY_COMBINATION_UNICORN_NPC = new AbnormalEffect("big_body_combination_unicorn_npc", 168);
    public static final /* enum */ AbnormalEffect BIG_BODY_COMBINATION_DEMON_NPC = new AbnormalEffect("big_body_combination_demon_npc", 169);
    public static final /* enum */ AbnormalEffect BIG_BODY_COMBINATION_CAT_PC = new AbnormalEffect("big_body_combination_cat_pc", 170);
    public static final /* enum */ AbnormalEffect BIG_BODY_COMBINATION_UNICORN_PC = new AbnormalEffect("big_body_combination_unicorn_pc", 171);
    public static final /* enum */ AbnormalEffect BIG_BODY_COMBINATION_DEMON_PC = new AbnormalEffect("big_body_combination_demon_pc", 172);
    public static final /* enum */ AbnormalEffect BIG_BODY_2 = new AbnormalEffect("big_body", 173);
    public static final /* enum */ AbnormalEffect LITTLE_BODY = new AbnormalEffect("little_body", 174);
    public static final /* enum */ AbnormalEffect PIRATE_SUIT = new AbnormalEffect("pirate_suit", 175);
    public static final /* enum */ AbnormalEffect DARK_ASSASSIN_SUIT = new AbnormalEffect("dark_assassin_suit", 176);
    public static final /* enum */ AbnormalEffect WHITE_ASSASSIN_SUIT = new AbnormalEffect("white_assassin_suit", 177);
    public static final /* enum */ AbnormalEffect MUSKETEER_SUIT = new AbnormalEffect("musketeer_suit", 178);
    public static final /* enum */ AbnormalEffect WIZARD_SUIT = new AbnormalEffect("wizard_suit", 179);
    public static final /* enum */ AbnormalEffect HALLOWEEN_SUIT_2 = new AbnormalEffect("halloween_suit_2", 180);
    public static final /* enum */ AbnormalEffect AVE_DRAGON_ULTIMATE = new AbnormalEffect("ave_dragon_ultimate", 181);
    public static final /* enum */ AbnormalEffect HALLOWEEN_SUIT = new AbnormalEffect("halloween_suit", 182);
    public static final /* enum */ AbnormalEffect INFINITE_SHIELD1_AVE = new AbnormalEffect("infinite_shield1_ave", 183);
    public static final /* enum */ AbnormalEffect INFINITE_SHIELD2_AVE = new AbnormalEffect("infinite_shield2_ave", 184);
    public static final /* enum */ AbnormalEffect INFINITE_SHIELD3_AVE = new AbnormalEffect("infinite_shield3_ave", 185);
    public static final /* enum */ AbnormalEffect INFINITE_SHIELD4_AVE = new AbnormalEffect("infinite_shield4_ave", 186);
    public static final /* enum */ AbnormalEffect AVE_ABSORB2_SHIELD = new AbnormalEffect("ave_absorb2_shield", 187);
    public static final /* enum */ AbnormalEffect UNK_188 = new AbnormalEffect("unk_188", 188);
    public static final /* enum */ AbnormalEffect UNK_189 = new AbnormalEffect("unk_189", 189);
    public static final /* enum */ AbnormalEffect TALISMAN_BAIUM = new AbnormalEffect("talisman_baium", 190);
    public static final /* enum */ AbnormalEffect UNK_191 = new AbnormalEffect("unk_191", 191);
    public static final /* enum */ AbnormalEffect UNK_192 = new AbnormalEffect("unk_192", 192);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM = new AbnormalEffect("changeshape_transform", 193);
    public static final /* enum */ AbnormalEffect ANGRY_GOLEM_AVE = new AbnormalEffect("angry_golem_ave", 194);
    public static final /* enum */ AbnormalEffect WA_UNBREAKABLE_SONIC_AVE = new AbnormalEffect("wa_unbreakable_sonic_ave", 195);
    public static final /* enum */ AbnormalEffect HEROIC_HOLY_AVE = new AbnormalEffect("heroic_holy_ave", 196);
    public static final /* enum */ AbnormalEffect HEROIC_SILENCE_AVE = new AbnormalEffect("heroic_silence_ave", 197);
    public static final /* enum */ AbnormalEffect HEROIC_FEAR_AVE_1 = new AbnormalEffect("heroic_fear_ave_1", 198);
    public static final /* enum */ AbnormalEffect HEROIC_FEAR_AVE_2 = new AbnormalEffect("heroic_fear_ave_2", 199);
    public static final /* enum */ AbnormalEffect AVE_BROOCH = new AbnormalEffect("ave_brooch", 200);
    public static final /* enum */ AbnormalEffect AVE_BROOCH_B = new AbnormalEffect("ave_brooch_b", 201);
    public static final /* enum */ AbnormalEffect INFINITE_SHIELD4_AVE_2 = new AbnormalEffect("infinite_shield4_ave_2", 206);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM_1 = new AbnormalEffect("changeshape_transform_1", 207);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM_2 = new AbnormalEffect("changeshape_transform_2", 208);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM_3 = new AbnormalEffect("changeshape_transform_3", 209);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM_4 = new AbnormalEffect("changeshape_transform_4", 210);
    public static final /* enum */ AbnormalEffect RO_COUNTER_TRASPIE = new AbnormalEffect("ro_counter_traspie", 215);
    public static final /* enum */ AbnormalEffect RO_GHOST_REFLECT = new AbnormalEffect("ro_ghost_reflect", 217);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM_5 = new AbnormalEffect("changeshape_transform_5", 218);
    public static final /* enum */ AbnormalEffect ICE_ELEMENTALDESTROY = new AbnormalEffect("ice_elementaldestroy", 219);
    public static final /* enum */ AbnormalEffect DORMANT_USER = new AbnormalEffect("dormant_user", 220);
    public static final /* enum */ AbnormalEffect NEWBIE_USER = new AbnormalEffect("newbie_user", 221);
    public static final /* enum */ AbnormalEffect THIRTEENTH_BUFF = new AbnormalEffect("thirteenth_buff", 222);
    public static final /* enum */ AbnormalEffect ARENA_UNSEAL_A = new AbnormalEffect("arena_unseal_a", 224);
    public static final /* enum */ AbnormalEffect ARENA_UNSEAL_B = new AbnormalEffect("arena_unseal_b", 225);
    public static final /* enum */ AbnormalEffect ARENA_UNSEAL_C = new AbnormalEffect("arena_unseal_c", 226);
    public static final /* enum */ AbnormalEffect ARENA_UNSEAL_D = new AbnormalEffect("arena_unseal_d", 227);
    public static final /* enum */ AbnormalEffect ARENA_UNSEAL_E = new AbnormalEffect("arena_unseal_e", 228);
    public static final /* enum */ AbnormalEffect IN_BATTLE_RHAPSODY = new AbnormalEffect("in_battle_rhapsody", 229);
    public static final /* enum */ AbnormalEffect IN_A_DECAL = new AbnormalEffect("in_a_decal", 230);
    public static final /* enum */ AbnormalEffect IN_B_DECAL = new AbnormalEffect("in_b_decal", 231);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM_6 = new AbnormalEffect("changeshape_transform_6", 232);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM_7 = new AbnormalEffect("changeshape_transform_7", 234);
    public static final /* enum */ AbnormalEffect SPIRIT_KING_WIND_AVE_B = new AbnormalEffect("spirit_king_wind_ave_b", 235);
    public static final /* enum */ AbnormalEffect EARTH_KING_BARRIER1_AVE = new AbnormalEffect("earth_king_barrier1_ave", 236);
    public static final /* enum */ AbnormalEffect EARTH_KING_BARRIER2_AVE = new AbnormalEffect("earth_king_barrier2_ave", 237);
    public static final /* enum */ AbnormalEffect FOCUS_SHIELD = new AbnormalEffect("focus_shield", 247);
    public static final /* enum */ AbnormalEffect RAISE_SHIELD = new AbnormalEffect("raise_shield", 248);
    public static final /* enum */ AbnormalEffect TRUE_VANGUARD = new AbnormalEffect("true_vanguard", 249);
    public static final /* enum */ AbnormalEffect SHIELD_WALL = new AbnormalEffect("shield_wall", 250);
    public static final /* enum */ AbnormalEffect FOOT_TRAIL = new AbnormalEffect("foot_trail", 251);
    public static final /* enum */ AbnormalEffect LEGEND_DECO_HERO = new AbnormalEffect("legend_deco_hero", 252);
    public static final /* enum */ AbnormalEffect CHANGESHAPE_TRANSFORM_8 = new AbnormalEffect("changeshape_transform_8", 253);
    public static final /* enum */ AbnormalEffect SPIRIT_KING_WIND_AVE = new AbnormalEffect("spirit_king_wind_ave", 254);
    public static final /* enum */ AbnormalEffect U098_BUFF_TA_DECO = new AbnormalEffect("u098_buff_ta_deco", 255);
    public static final /* enum */ AbnormalEffect ORFEN_ENERGY1_AVE = new AbnormalEffect("orfen_energy1_ave", 256);
    public static final /* enum */ AbnormalEffect ORFEN_ENERGY2_AVE = new AbnormalEffect("orfen_energy2_ave", 257);
    public static final /* enum */ AbnormalEffect ORFEN_ENERGY3_AVE = new AbnormalEffect("orfen_energy3_ave", 258);
    public static final /* enum */ AbnormalEffect ORFEN_ENERGY4_AVE = new AbnormalEffect("orfen_energy4_ave", 259);
    public static final /* enum */ AbnormalEffect ORFEN_ENERGY5_AVE = new AbnormalEffect("orfen_energy5_ave", 260);
    public static final /* enum */ AbnormalEffect UNHOLY_BARRIER_AVE = new AbnormalEffect("unholy_barrier_ave", 263);
    public static final /* enum */ AbnormalEffect RUDOLF_A_AVE = new AbnormalEffect("rudolf_a_ave", 266);
    public static final /* enum */ AbnormalEffect RUDOLF_B_AVE = new AbnormalEffect("rudolf_b_ave", 267);
    public static final /* enum */ AbnormalEffect RUDOLF_C_AVE = new AbnormalEffect("rudolf_c_ave", 268);
    public static final /* enum */ AbnormalEffect OLYMPIAD_MEDAL_AVE = new AbnormalEffect("olympiad_medal_ave", 269);
    public static final /* enum */ AbnormalEffect OLYMPIAD_SPORT_A_AVE = new AbnormalEffect("olympiad_sport_a_ave", 270);
    public static final /* enum */ AbnormalEffect OLYMPIAD_SPORT_B_AVE = new AbnormalEffect("olympiad_sport_b_ave", 271);
    public static final /* enum */ AbnormalEffect OLYMPIAD_SPORT_C_AVE = new AbnormalEffect("olympiad_sport_c_ave", 272);
    public static final /* enum */ AbnormalEffect D_CHAOS_MATCH_DECO_SMALL = new AbnormalEffect("d_chaos_match_deco_small", 273);
    public static final /* enum */ AbnormalEffect TRANS_DECO_R = new AbnormalEffect("trans_deco_r", 274);
    public static final /* enum */ AbnormalEffect TRANS_DECO_B = new AbnormalEffect("trans_deco_b", 275);
    public static final /* enum */ AbnormalEffect TRANS_DECO_Y = new AbnormalEffect("trans_deco_y", 276);
    public static final /* enum */ AbnormalEffect TRANS_DECO_G = new AbnormalEffect("trans_deco_g", 277);
    public static final /* enum */ AbnormalEffect TRANS_DECO_P = new AbnormalEffect("trans_deco_p", 278);
    public static final /* enum */ AbnormalEffect TRANS_DECO_P2 = new AbnormalEffect("trans_deco_p2", 279);
    public static final /* enum */ AbnormalEffect TRANS_DECO_W = new AbnormalEffect("trans_deco_w", 280);
    public static final /* enum */ AbnormalEffect TRANS_DECO_R2 = new AbnormalEffect("trans_deco_r2", 281);
    public static final /* enum */ AbnormalEffect TRANS_DECO_W2 = new AbnormalEffect("trans_deco_w2", 282);
    public static final /* enum */ AbnormalEffect HDDOWN_AVE = new AbnormalEffect("hddown_ave", 283);
    public static final /* enum */ AbnormalEffect HDMDOWN_AVE = new AbnormalEffect("hdmdown_ave", 284);
    public static final /* enum */ AbnormalEffect KISSNHEART_AVE = new AbnormalEffect("kissnheart_ave", 286);
    public static final /* enum */ AbnormalEffect EARTH_BARRIER_AVE = new AbnormalEffect("earth_barrier_ave", 287);
    public static final /* enum */ AbnormalEffect LILITH_DARK_BARRIER_AVE = new AbnormalEffect("lilith_dark_barrier_ave", 288);
    public static final /* enum */ AbnormalEffect EARTH_BARRIER2_AVE = new AbnormalEffect("earth_barrier2_ave", 289);
    public static final /* enum */ AbnormalEffect CROFFIN_QUEEN_INVINCIBILITY_AVE = new AbnormalEffect("croffin_queen_invincibility_ave", 290);
    public static final /* enum */ AbnormalEffect MPDOWN_AVE = new AbnormalEffect("mpdown_ave", 291);
    public static final /* enum */ AbnormalEffect WORLDCUP_RED_AVE = new AbnormalEffect("worldcup_red_ave", 292);
    public static final /* enum */ AbnormalEffect WORLDCUP_BLUE_AVE = new AbnormalEffect("worldcup_blue_ave", 293);
    public static final /* enum */ AbnormalEffect SURGEWAVE_AVE = new AbnormalEffect("surgewave_ave", 296);
    public static final /* enum */ AbnormalEffect BLESS_AVE = new AbnormalEffect("bless_ave", 297);
    public static final /* enum */ AbnormalEffect ANTHARAS_RAGE_AVE = new AbnormalEffect("antharas_rage_ave", 298);
    public static final /* enum */ AbnormalEffect G_BARRIER_AVE = new AbnormalEffect("g_barrier_ave", 302);
    public static final /* enum */ AbnormalEffect FIREWORKS_001T = new AbnormalEffect("fireworks_001t", 304);
    public static final /* enum */ AbnormalEffect FIREWORKS_002T = new AbnormalEffect("fireworks_002t", 305);
    public static final /* enum */ AbnormalEffect FIREWORKS_003T = new AbnormalEffect("fireworks_003t", 306);
    public static final /* enum */ AbnormalEffect FIREWORKS_004T = new AbnormalEffect("fireworks_004t", 307);
    public static final /* enum */ AbnormalEffect FIREWORKS_005T = new AbnormalEffect("fireworks_005t", 308);
    public static final /* enum */ AbnormalEffect FIREWORKS_006T = new AbnormalEffect("fireworks_006t", 309);
    public static final /* enum */ AbnormalEffect FIREWORKS_007T = new AbnormalEffect("fireworks_007t", 310);
    public static final /* enum */ AbnormalEffect FIREWORKS_008T = new AbnormalEffect("fireworks_008t", 311);
    public static final /* enum */ AbnormalEffect FIREWORKS_009T = new AbnormalEffect("fireworks_009t", 312);
    public static final /* enum */ AbnormalEffect FIREWORKS_010T = new AbnormalEffect("fireworks_010t", 313);
    public static final /* enum */ AbnormalEffect FIREWORKS_011T = new AbnormalEffect("fireworks_011t", 314);
    public static final /* enum */ AbnormalEffect FIREWORKS_012T = new AbnormalEffect("fireworks_012t", 315);
    public static final /* enum */ AbnormalEffect FIREWORKS_013T = new AbnormalEffect("fireworks_013t", 316);
    public static final /* enum */ AbnormalEffect FIREWORKS_014T = new AbnormalEffect("fireworks_014t", 317);
    public static final /* enum */ AbnormalEffect FIREWORKS_015T = new AbnormalEffect("fireworks_015t", 318);
    public static final /* enum */ AbnormalEffect P_CAKE_AVE = new AbnormalEffect("p_cake_ave", 319);
    public static final /* enum */ AbnormalEffect ZARICHE_PRISION_AVE = new AbnormalEffect("zariche_prision_ave", 323);
    public static final /* enum */ AbnormalEffect RUDOLPH = new AbnormalEffect("rudolph", 324);
    public static final /* enum */ AbnormalEffect XMAS_HEART_AVE = new AbnormalEffect("xmas_heart_ave", 325);
    public static final /* enum */ AbnormalEffect XMAS_HAND_AVE = new AbnormalEffect("xmas_hand_ave", 326);
    public static final /* enum */ AbnormalEffect LUCKYBAG_AVE = new AbnormalEffect("luckybag_ave", 327);
    public static final /* enum */ AbnormalEffect HEROIC_MIRACLE_AVE = new AbnormalEffect("heroic_miracle_ave", 328);
    public static final /* enum */ AbnormalEffect POCKETPIG_AVE = new AbnormalEffect("pocketpig_ave", 329);
    public static final /* enum */ AbnormalEffect BLACK_STANCE_AVE = new AbnormalEffect("black_stance_ave", 330);
    public static final /* enum */ AbnormalEffect BLACK_TRANS_DECO_AVE = new AbnormalEffect("black_trans_deco_ave", 330);
    public static final /* enum */ AbnormalEffect KAMAEL_BLACK_TRANSFORM = new AbnormalEffect("kamael_black_transform", 331);
    public static final /* enum */ AbnormalEffect WHITE_STANCE_AVE = new AbnormalEffect("white_stance_ave", 332);
    public static final /* enum */ AbnormalEffect HEAL_DECO_AVE = new AbnormalEffect("heal_deco_ave", 332);
    public static final /* enum */ AbnormalEffect KAMAEL_WHITE_TRANSFORM = new AbnormalEffect("kamael_white_transform", 333);
    public static final /* enum */ AbnormalEffect LONG_RAPIER_WHITE_AVE = new AbnormalEffect("long_rapier_white_ave", 334);
    public static final /* enum */ AbnormalEffect LONG_RAPIER_BLACK_AVE = new AbnormalEffect("long_rapier_black_ave", 335);
    public static final /* enum */ AbnormalEffect ZARICHE_PRISION2_AVE = new AbnormalEffect("zariche_prision2_ave", 336);
    public static final /* enum */ AbnormalEffect BLUEHEART_AVE = new AbnormalEffect("blueheart_ave", 337);
    public static final /* enum */ AbnormalEffect ATTACK_BUFF_AVE = new AbnormalEffect("attack_buff_ave", 338);
    public static final /* enum */ AbnormalEffect SHIELD_BUFF_AVE = new AbnormalEffect("shield_buff_ave", 339);
    public static final /* enum */ AbnormalEffect BERSERKER_BUFF_AVE = new AbnormalEffect("berserker_buff_ave", 340);
    public static final /* enum */ AbnormalEffect DRAGON_ULTIMATE = new AbnormalEffect("dragon_ultimate", 700);
    public static final /* enum */ AbnormalEffect CHANGE_HALLOWEEN = new AbnormalEffect("change_halloween", 1000);
    public static final /* enum */ AbnormalEffect BR_Y_1_ACCESSORY_R_RING = new AbnormalEffect("br_y_1_accessory_r_ring", 10001);
    public static final /* enum */ AbnormalEffect BR_Y_1_ACCESSORY_EARRING = new AbnormalEffect("br_y_1_accessory_earring", 10002);
    public static final /* enum */ AbnormalEffect BR_Y_1_ACCESSORY_NECKRACE = new AbnormalEffect("br_y_1_accessory_neckrace", 10003);
    public static final /* enum */ AbnormalEffect BR_Y_2_ACCESSORY_R_RING = new AbnormalEffect("br_y_2_accessory_r_ring", 10004);
    public static final /* enum */ AbnormalEffect BR_Y_2_ACCESSORY_EARRING = new AbnormalEffect("br_y_2_accessory_earring", 10005);
    public static final /* enum */ AbnormalEffect BR_Y_2_ACCESSORY_NECKRACE = new AbnormalEffect("br_y_2_accessory_neckrace", 10006);
    public static final /* enum */ AbnormalEffect BR_Y_3_ACCESSORY_R_RING = new AbnormalEffect("br_y_3_accessory_r_ring", 10007);
    public static final /* enum */ AbnormalEffect BR_Y_3_ACCESSORY_EARRING = new AbnormalEffect("br_y_3_accessory_earring", 10008);
    public static final /* enum */ AbnormalEffect BR_Y_3_ACCESSORY_NECKRACE = new AbnormalEffect("br_y_3_accessory_neckrace", 10009);
    public static final /* enum */ AbnormalEffect BR_TALI_DECO = new AbnormalEffect("br_tali_deco", 10019);
    public static final /* enum */ AbnormalEffect BASEBALL_UNIFORM = new AbnormalEffect("baseball_uniform", 10020);
    public static final /* enum */ AbnormalEffect SANTA_CLAUS_LIGHT = new AbnormalEffect("santa_claus_light_glow", 10021);
    public static final /* enum */ AbnormalEffect SANTA_CLAUS_BLACK = new AbnormalEffect("santa_claus_black_glow", 10022);
    public static final /* enum */ AbnormalEffect SANTA_CLAUS_RED = new AbnormalEffect("santa_claus_red_glow", 10023);
    public static final /* enum */ AbnormalEffect SCHOOL_UNIFORM_LIGHT = new AbnormalEffect("school_uniform_light_glow", 10024);
    public static final /* enum */ AbnormalEffect SCHOOL_UNIFORM_BLACK = new AbnormalEffect("school_uniform_black_glow", 10025);
    public static final /* enum */ AbnormalEffect SCHOOL_UNIFORM_RED = new AbnormalEffect("school_uniform_red_glow", 10026);
    public static final /* enum */ AbnormalEffect BEACH_SWIMSUIT_LIGHT = new AbnormalEffect("beach_swimsuit_light", 10027);
    public static final /* enum */ AbnormalEffect BEACH_SWIMSUIT_BLACK = new AbnormalEffect("beach_swimsuit_black", 10028);
    public static final /* enum */ AbnormalEffect BEACH_SWIMSUIT_RED = new AbnormalEffect("beach_swimsuit_red", 10029);
    public static final /* enum */ AbnormalEffect TEDDY_BEAR_LIGHT = new AbnormalEffect("teddy_bear_light", 10030);
    public static final /* enum */ AbnormalEffect TEDDY_BEAR_BLACK = new AbnormalEffect("teddy_bear_black", 10031);
    public static final /* enum */ AbnormalEffect TEDDY_BEAR_RED = new AbnormalEffect("teddy_bear_red", 10032);
    public static final /* enum */ AbnormalEffect TOY_CAT_LIGHT = new AbnormalEffect("toy_cat_light", 10033);
    public static final /* enum */ AbnormalEffect TOY_CAT_BLACK = new AbnormalEffect("toy_cat_black", 10034);
    public static final /* enum */ AbnormalEffect TOY_CAT_RED = new AbnormalEffect("toy_cat_red", 10035);
    public static final /* enum */ AbnormalEffect TOY_PANDA_LIGHT = new AbnormalEffect("toy_panda_light", 10036);
    public static final /* enum */ AbnormalEffect TOY_PANDA_BLACK = new AbnormalEffect("toy_panda_black", 10037);
    public static final /* enum */ AbnormalEffect TOY_PANDA_RED = new AbnormalEffect("toy_panda_red", 10038);
    public static final /* enum */ AbnormalEffect BASEBALL_UNIFORM_LIGHT = new AbnormalEffect("baseball_uniform_light", 10039);
    public static final /* enum */ AbnormalEffect BASEBALL_UNIFORM_BLACK = new AbnormalEffect("baseball_uniform_black", 10040);
    public static final /* enum */ AbnormalEffect BASEBALL_UNIFORM_RED = new AbnormalEffect("baseball_uniform_red", 10041);
    public static final /* enum */ AbnormalEffect SEDUCTIVE_LIGHT = new AbnormalEffect("seductive_light", 10042);
    public static final /* enum */ AbnormalEffect SEDUCTIVE_BLACK = new AbnormalEffect("seductive_black", 10043);
    public static final /* enum */ AbnormalEffect SEDUCTIVE_RED = new AbnormalEffect("seductive_red", 10044);
    public static final /* enum */ AbnormalEffect BLACK_SCHOOL_UNIFORM_LIGHT = new AbnormalEffect("black_school_uniform_light", 10045);
    public static final /* enum */ AbnormalEffect BLACK_SCHOOL_UNIFORM_BLACK = new AbnormalEffect("black_school_uniform_black", 10046);
    public static final /* enum */ AbnormalEffect BLACK_SCHOOL_UNIFORM_RED = new AbnormalEffect("black_school_uniform_red", 10047);
    public static final /* enum */ AbnormalEffect HANBOK_LIGHT = new AbnormalEffect("hanbok_light", 10048);
    public static final /* enum */ AbnormalEffect HANBOK_BLACK = new AbnormalEffect("hanbok_black", 10049);
    public static final /* enum */ AbnormalEffect HANBOK_RED = new AbnormalEffect("hanbok_red", 10050);
    public static final /* enum */ AbnormalEffect METAL_SUIT_LIGHT = new AbnormalEffect("metal_suit_light", 10051);
    public static final /* enum */ AbnormalEffect METAL_SUIT_BLACK = new AbnormalEffect("metal_suit_black", 10052);
    public static final /* enum */ AbnormalEffect METAL_SUIT_RED = new AbnormalEffect("metal_suit_red", 10053);
    public static final /* enum */ AbnormalEffect SAMURAI_LIGHT = new AbnormalEffect("samurai_light", 10054);
    public static final /* enum */ AbnormalEffect SAMURAI_BLACK = new AbnormalEffect("samurai_black", 10055);
    public static final /* enum */ AbnormalEffect SAMURAI_RED = new AbnormalEffect("samurai_red", 10056);
    public static final /* enum */ AbnormalEffect GREEN_ARCHER_LIGHT = new AbnormalEffect("green_archer_light", 10057);
    public static final /* enum */ AbnormalEffect GREEN_ARCHER_BLACK = new AbnormalEffect("green_archer_black", 10058);
    public static final /* enum */ AbnormalEffect GREEN_ARCHER_RED = new AbnormalEffect("green_archer_red", 10059);
    public static final /* enum */ AbnormalEffect FORMAL_WEAR_LIGHT = new AbnormalEffect("formal_wear_light", 10060);
    public static final /* enum */ AbnormalEffect FORMAL_WEAR_BLACK = new AbnormalEffect("formal_wear_black", 10061);
    public static final /* enum */ AbnormalEffect FORMAL_WEAR_RED = new AbnormalEffect("formal_wear_red", 10062);
    public static final /* enum */ AbnormalEffect KAT_THE_CAT_LIGHT = new AbnormalEffect("kat_the_cat_light", 10063);
    public static final /* enum */ AbnormalEffect KAT_THE_CAT_BLACK = new AbnormalEffect("kat_the_cat_black", 10064);
    public static final /* enum */ AbnormalEffect KAT_THE_CAT_RED = new AbnormalEffect("kat_the_cat_red", 10065);
    public static final /* enum */ AbnormalEffect HALLOWEEN_LIGHT = new AbnormalEffect("halloween_light", 10066);
    public static final /* enum */ AbnormalEffect HALLOWEEN_BLACK = new AbnormalEffect("halloween_black", 10067);
    public static final /* enum */ AbnormalEffect HALLOWEEN_RED = new AbnormalEffect("halloween_red", 10068);
    public static final /* enum */ AbnormalEffect ALLURING_SWIMSUIT_LIGHT = new AbnormalEffect("alluring_swimsuit_light", 10069);
    public static final /* enum */ AbnormalEffect ALLURING_SWIMSUIT_BLACK = new AbnormalEffect("alluring_swimsuit_black", 10070);
    public static final /* enum */ AbnormalEffect ALLURING_SWIMSUIT_RED = new AbnormalEffect("alluring_swimsuit_red", 10071);
    public static final /* enum */ AbnormalEffect VAMPIRE_LIGHT = new AbnormalEffect("vampire_light", 10072);
    public static final /* enum */ AbnormalEffect VAMPIRE_BLACK = new AbnormalEffect("vampire_black", 10073);
    public static final /* enum */ AbnormalEffect VAMPIRE_RED = new AbnormalEffect("vampire_red", 10074);
    public static final /* enum */ AbnormalEffect DARK_KNIGHT_LIGHT = new AbnormalEffect("dark_knight_light", 10075);
    public static final /* enum */ AbnormalEffect DARK_KNIGHT_BLACK = new AbnormalEffect("dark_knight_black", 10076);
    public static final /* enum */ AbnormalEffect DARK_KNIGHT_RED = new AbnormalEffect("dark_knight_red", 10077);
    public static final /* enum */ AbnormalEffect CHEVALIER_LIGHT = new AbnormalEffect("chevalier_light", 10078);
    public static final /* enum */ AbnormalEffect CHEVALIER_BLACK = new AbnormalEffect("chevalier_black", 10079);
    public static final /* enum */ AbnormalEffect CHEVALIER_RED = new AbnormalEffect("chevalier_red", 10080);
    public static final /* enum */ AbnormalEffect RED_ARCHER_LIGHT = new AbnormalEffect("red_archer_light", 10081);
    public static final /* enum */ AbnormalEffect RED_ARCHER_BLACK = new AbnormalEffect("red_archer_black", 10082);
    public static final /* enum */ AbnormalEffect RED_ARCHER_RED = new AbnormalEffect("red_archer_red", 10083);
    public static final /* enum */ AbnormalEffect BLUE_PIRATE_LIGHT = new AbnormalEffect("blue_pirate_light", 10084);
    public static final /* enum */ AbnormalEffect BLUE_PIRATE_BLACK = new AbnormalEffect("blue_pirate_black", 10085);
    public static final /* enum */ AbnormalEffect BLUE_PIRATE_RED = new AbnormalEffect("blue_pirate_red", 10086);
    public static final /* enum */ AbnormalEffect DARK_RED_WIZARD_LIGHT = new AbnormalEffect("dark_red_wizard_light", 10087);
    public static final /* enum */ AbnormalEffect DARK_RED_WIZARD_BLACK = new AbnormalEffect("dark_red_wizard_black", 10088);
    public static final /* enum */ AbnormalEffect DARK_RED_WIZARD_RED = new AbnormalEffect("dark_red_wizard_red", 10089);
    public static final /* enum */ AbnormalEffect MYSTIC_LIGHT = new AbnormalEffect("mystic_light", 10090);
    public static final /* enum */ AbnormalEffect MYSTIC_BLACK = new AbnormalEffect("mystic_black", 10091);
    public static final /* enum */ AbnormalEffect MYSTIC_RED = new AbnormalEffect("mystic_red", 10092);
    public static final /* enum */ AbnormalEffect BLACK_PIRATE_LIGHT = new AbnormalEffect("black_pirate_light", 10093);
    public static final /* enum */ AbnormalEffect BLACK_PIRATE_BLACK = new AbnormalEffect("black_pirate_black", 10094);
    public static final /* enum */ AbnormalEffect BLACK_PIRATE_RED = new AbnormalEffect("black_pirate_red", 10095);
    public static final /* enum */ AbnormalEffect RED_NOBLESSE_LIGHT = new AbnormalEffect("red_noblesse_light", 10096);
    public static final /* enum */ AbnormalEffect RED_NOBLESSE_BLACK = new AbnormalEffect("red_noblesse_black", 10097);
    public static final /* enum */ AbnormalEffect RED_NOBLESSE_RED = new AbnormalEffect("red_noblesse_red", 10098);
    public static final /* enum */ AbnormalEffect BARBARIAN_WOLF_LIGHT = new AbnormalEffect("barbarian_wolf_light", 10099);
    public static final /* enum */ AbnormalEffect BARBARIAN_WOLF_BLACK = new AbnormalEffect("barbarian_wolf_black", 10100);
    public static final /* enum */ AbnormalEffect BARBARIAN_WOLF_RED = new AbnormalEffect("barbarian_wolf_red", 10101);
    public static final /* enum */ AbnormalEffect VALKYRIE_LIGHT = new AbnormalEffect("valkyrie_light", 10102);
    public static final /* enum */ AbnormalEffect VALKYRIE_BLACK = new AbnormalEffect("valkyrie_black", 10103);
    public static final /* enum */ AbnormalEffect VALKYRIE_RED = new AbnormalEffect("valkyrie_red", 10104);
    public static final /* enum */ AbnormalEffect KELBIM_LIGHT = new AbnormalEffect("kelbim_light", 10105);
    public static final /* enum */ AbnormalEffect KELBIM_BLACK = new AbnormalEffect("kelbim_black", 10106);
    public static final /* enum */ AbnormalEffect KELBIM_RED = new AbnormalEffect("kelbim_red", 10107);
    public static final /* enum */ AbnormalEffect NINJA_LIGHT = new AbnormalEffect("ninja_light", 10108);
    public static final /* enum */ AbnormalEffect NINJA_BLACK = new AbnormalEffect("ninja_black", 10109);
    public static final /* enum */ AbnormalEffect NINJA_RED = new AbnormalEffect("ninja_red", 10110);
    public static final /* enum */ AbnormalEffect HIGH_PRIEST_LIGHT = new AbnormalEffect("high_priest_light", 10111);
    public static final /* enum */ AbnormalEffect HIGH_PRIEST_BLACK = new AbnormalEffect("high_priest_black", 10112);
    public static final /* enum */ AbnormalEffect HIGH_PRIEST_RED = new AbnormalEffect("high_priest_red", 10113);
    public static final /* enum */ AbnormalEffect WHITE_NOBLESSE_LIGHT = new AbnormalEffect("white_noblesse_light", 10114);
    public static final /* enum */ AbnormalEffect WHITE_NOBLESSE_BLACK = new AbnormalEffect("white_noblesse_black", 10115);
    public static final /* enum */ AbnormalEffect WHITE_NOBLESSE_RED = new AbnormalEffect("white_noblesse_red", 10116);
    public static final /* enum */ AbnormalEffect PURPLE_COWBOY_LIGHT = new AbnormalEffect("purple_cowboy_light", 10117);
    public static final /* enum */ AbnormalEffect PURPLE_COWBOY_BLACK = new AbnormalEffect("purple_cowboy_black", 10118);
    public static final /* enum */ AbnormalEffect PURPLE_COWBOY_RED = new AbnormalEffect("purple_cowboy_red", 10119);
    public static final /* enum */ AbnormalEffect BLUE_MUSKETEER_LIGHT = new AbnormalEffect("blue_musketeer_light", 10120);
    public static final /* enum */ AbnormalEffect BLUE_MUSKETEER_BLACK = new AbnormalEffect("blue_musketeer_black", 10121);
    public static final /* enum */ AbnormalEffect BLUE_MUSKETEER_RED = new AbnormalEffect("blue_musketeer_red", 10122);
    public static final /* enum */ AbnormalEffect ZAKEN_LIGHT = new AbnormalEffect("zaken_light", 10123);
    public static final /* enum */ AbnormalEffect ZAKEN_BLACK = new AbnormalEffect("zaken_black", 10124);
    public static final /* enum */ AbnormalEffect ZAKEN_RED = new AbnormalEffect("zaken_red", 10125);
    public static final /* enum */ AbnormalEffect DRAGON_LIGHT = new AbnormalEffect("dragon_light", 10126);
    public static final /* enum */ AbnormalEffect DRAGON_BLACK = new AbnormalEffect("dragon_black", 10127);
    public static final /* enum */ AbnormalEffect DRAGON_RED = new AbnormalEffect("dragon_red", 10128);
    public static final /* enum */ AbnormalEffect ANAKIM_LIGHT = new AbnormalEffect("anakim_light", 10129);
    public static final /* enum */ AbnormalEffect ANAKIM_BLACK = new AbnormalEffect("anakim_black", 10130);
    public static final /* enum */ AbnormalEffect ANAKIM_RED = new AbnormalEffect("anakim_red", 10131);
    public static final /* enum */ AbnormalEffect LILITH_LIGHT = new AbnormalEffect("lilith_light", 10132);
    public static final /* enum */ AbnormalEffect LILITH_BLACK = new AbnormalEffect("lilith_black", 10133);
    public static final /* enum */ AbnormalEffect LILITH_RED = new AbnormalEffect("lilith_red", 10134);
    public static final /* enum */ AbnormalEffect FREYA_LIGHT = new AbnormalEffect("freya_light", 10135);
    public static final /* enum */ AbnormalEffect FREYA_BLACK = new AbnormalEffect("freya_black", 10136);
    public static final /* enum */ AbnormalEffect FREYA_RED = new AbnormalEffect("freya_red", 10137);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL1 = new AbnormalEffect("custom_abnormal1", 19040);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL2 = new AbnormalEffect("custom_abnormal2", 19041);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL3 = new AbnormalEffect("custom_abnormal3", 19042);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL4 = new AbnormalEffect("custom_abnormal4", 19043);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL5 = new AbnormalEffect("custom_abnormal5", 19044);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL6 = new AbnormalEffect("custom_abnormal6", 19045);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL7 = new AbnormalEffect("custom_abnormal7", 19046);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL8 = new AbnormalEffect("custom_abnormal8", 19047);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL9 = new AbnormalEffect("custom_abnormal9", 19048);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL10 = new AbnormalEffect("custom_abnormal10", 19049);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL11 = new AbnormalEffect("custom_abnormal11", 19050);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL12 = new AbnormalEffect("custom_abnormal12", 19051);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL13 = new AbnormalEffect("custom_abnormal13", 19052);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL14 = new AbnormalEffect("custom_abnormal14", 19053);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL15 = new AbnormalEffect("custom_abnormal15", 19054);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL16 = new AbnormalEffect("custom_abnormal16", 19055);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL17 = new AbnormalEffect("custom_abnormal17", 19056);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL18 = new AbnormalEffect("custom_abnormal18", 19057);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL19 = new AbnormalEffect("custom_abnormal19", 19058);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL20 = new AbnormalEffect("custom_abnormal20", 19059);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL21 = new AbnormalEffect("custom_abnormal21", 19060);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL22 = new AbnormalEffect("custom_abnormal22", 19061);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL23 = new AbnormalEffect("custom_abnormal23", 19062);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL24 = new AbnormalEffect("custom_abnormal24", 19063);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL25 = new AbnormalEffect("custom_abnormal25", 19064);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL26 = new AbnormalEffect("custom_abnormal26", 19065);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL27 = new AbnormalEffect("custom_abnormal27", 19066);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL28 = new AbnormalEffect("custom_abnormal28", 19067);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL29 = new AbnormalEffect("custom_abnormal29", 19068);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL30 = new AbnormalEffect("custom_abnormal30", 19069);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL31 = new AbnormalEffect("custom_abnormal31", 19070);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL32 = new AbnormalEffect("custom_abnormal32", 19071);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL33 = new AbnormalEffect("custom_abnormal33", 19072);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL34 = new AbnormalEffect("custom_abnormal34", 19073);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL35 = new AbnormalEffect("custom_abnormal35", 19074);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL36 = new AbnormalEffect("custom_abnormal36", 19075);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL37 = new AbnormalEffect("custom_abnormal37", 19076);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL38 = new AbnormalEffect("custom_abnormal38", 19077);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL39 = new AbnormalEffect("custom_abnormal39", 19078);
    public static final /* enum */ AbnormalEffect CUSTOM_ABNORMAL40 = new AbnormalEffect("custom_abnormal40", 19079);
    private int pa;
    private final String fU;
    private AbnormalEffectType a;
    public static final AbnormalEffect[] EMPTY_ARRAY;
    private final int CQ;
    private static final /* synthetic */ AbnormalEffect[] c;

    public static AbnormalEffect[] values() {
        return (AbnormalEffect[])c.clone();
    }

    public static AbnormalEffect valueOf(String string) {
        return Enum.valueOf(AbnormalEffect.class, string);
    }

    private AbnormalEffect(String string2, int n2) {
        this.fU = string2;
        this.CQ = n2;
    }

    private AbnormalEffect(String string2, int n2, AbnormalEffectType abnormalEffectType) {
        this.fU = string2;
        this.pa = n2;
        this.a = abnormalEffectType;
        this.CQ = 0;
    }

    public int getClientId() {
        return this.CQ;
    }

    public final int getMask() {
        return this.pa;
    }

    public final String getName() {
        return this.fU;
    }

    public AbnormalEffectType getType() {
        return this.a;
    }

    public static AbnormalEffect getByName(String string) {
        for (AbnormalEffect abnormalEffect : AbnormalEffect.values()) {
            if (!abnormalEffect.getName().equals(string)) continue;
            return abnormalEffect;
        }
        throw new NoSuchElementException("AbnormalEffect not found for name: '" + string + "'.\n Please check " + AbnormalEffect.class.getCanonicalName());
    }

    private static /* synthetic */ AbnormalEffect[] a() {
        return new AbnormalEffect[]{NULL, DOT_BLEEDING, DOT_POISON, DOT_FIRE, DOT_WATER, DOT_WIND, DOT_SOIL, STUN, SLEEP, SILENCE, ROOT, PARALYZE, FLESH_STONE, DOT_MP, BIG_HEAD, DOT_FIRE_AREA, CHANGE_TEXTURE, BIG_BODY, FLOATING_ROOT, DANCE_ROOT, GHOST_STUN, STEALTH, SEIZURE1, SEIZURE2, MAGIC_SQUARE, FREEZING, SHAKE, ULTIMATE_DEFENCE, VP_UP, VP_KEEP, REAL_TARGET, DEATH_MARK, TURN_FLEE, INVINCIBILITY, AIR_BATTLE_SLOW, AIR_BATTLE_ROOT, CHANGE_WP, CHANGE_HAIR_G, CHANGE_HAIR_P, CHANGE_HAIR_B, UNKNOWN_40, STIGMA_OF_SILEN, SPEED_DOWN, FROZEN_PILLAR, CHANGE_VES_S, CHANGE_VES_C, CHANGE_VES_D, TIME_BOMB, MP_SHIELD, AIRBIND, CHANGEBODY, KNOCKDOWN, NAVIT_ADVENT, KNOCKBACK, CHANGE_7ANNIVERSARY, ON_SPOT_MOVEMENT, DEPORT, AURA_BUFF, AURA_BUFF_SELF, AURA_DEBUFF, AURA_DEBUFF_SELF, HURRICANE, HURRICANE_SELF, BLACK_MARK, BR_SOUL_AVATAR, CHANGE_GRADE_B, BR_BEAM_SWORD_ONEHAND, BR_BEAM_SWORD_DUAL, NO_CHAT, HERB_PA_UP, HERB_MA_UP, SEED_TALISMAN1, SEED_TALISMAN2, SEED_TALISMAN3, SEED_TALISMAN4, SEED_TALISMAN5, SEED_TALISMAN6, CURIOUS_HOUSE, NGRADE_CHANGE, DGRADE_CHANGE, CGRADE_CHANGE, BGRADE_CHANGE, AGRADE_CHANGE, SWEET_ICE_FLAKES, FANTASY_ICE_FLAKES, CHANGE_XMAS, CARD_PC_DECO, CHANGE_DINOS, CHANGE_VALENTINE, CHOCOLATE, CANDY, COOKIE, STARS_0, STARS_1, STARS_2, STARS_3, STARS_4, STARS_5, DUELING, FREEZING2, CHANGE_YOGI, YOGI, MUSICAL_NOTE_YELLOW, MUSICAL_NOTE_BLUE, MUSICAL_NOTE_GREEN, TENTH_ANNIVERSARY, XMAS_SOCKS, XMAS_TREE, XMAS_SNOWMAN, OTHELL_ROGUE_BLUFF, HE_PROTECT, SU_SUMCROSS, WIND_STUN, STORM_SIGN2, STORM_SIGN1, WIND_BLEND, DECEPTIVE_BLINK, WIND_HIDE, PSY_POWER, SQUALL, WIND_ILLUSION, SAYHA_FURY, HIDE4, PMENTAL_TRAIL, HOLD_LIGHTING, GRAVITY_SPACE_3, SPACEREF, HE_ASPECT, RUNWAY_ARMOR1, RUNWAY_ARMOR2, RUNWAY_ARMOR3, RUNWAY_ARMOR4, RUNWAY_ARMOR5, RUNWAY_ARMOR6, RUNWAY_WEAPON1, RUNWAY_WEAPON2, PALADIN_PROTECTION, SENTINEL_PROTECTION, REAL_TARGET_2, DIVINITY, SHILLIEN_PROTECTION, EVENT_STARS_0, EVENT_STARS_1, EVENT_STARS_2, EVENT_STARS_3, EVENT_STARS_4, EVENT_STARS_5, ABSORB_SHIELD, PHOENIX_AURA, REVENGE_AURA, EVAS_AURA, TEMPLAR_AURA, LONG_BLOW, WIDE_SWORD, BIG_FIST, SHADOW_STEP, TORNADO, SNOW_SLOW, SNOW_HOLD, UNK_164, TORNADO_SLOW, ASTATINE_WATER, BIG_BODY_COMBINATION_CAT_NPC, BIG_BODY_COMBINATION_UNICORN_NPC, BIG_BODY_COMBINATION_DEMON_NPC, BIG_BODY_COMBINATION_CAT_PC, BIG_BODY_COMBINATION_UNICORN_PC, BIG_BODY_COMBINATION_DEMON_PC, BIG_BODY_2, LITTLE_BODY, PIRATE_SUIT, DARK_ASSASSIN_SUIT, WHITE_ASSASSIN_SUIT, MUSKETEER_SUIT, WIZARD_SUIT, HALLOWEEN_SUIT_2, AVE_DRAGON_ULTIMATE, HALLOWEEN_SUIT, INFINITE_SHIELD1_AVE, INFINITE_SHIELD2_AVE, INFINITE_SHIELD3_AVE, INFINITE_SHIELD4_AVE, AVE_ABSORB2_SHIELD, UNK_188, UNK_189, TALISMAN_BAIUM, UNK_191, UNK_192, CHANGESHAPE_TRANSFORM, ANGRY_GOLEM_AVE, WA_UNBREAKABLE_SONIC_AVE, HEROIC_HOLY_AVE, HEROIC_SILENCE_AVE, HEROIC_FEAR_AVE_1, HEROIC_FEAR_AVE_2, AVE_BROOCH, AVE_BROOCH_B, INFINITE_SHIELD4_AVE_2, CHANGESHAPE_TRANSFORM_1, CHANGESHAPE_TRANSFORM_2, CHANGESHAPE_TRANSFORM_3, CHANGESHAPE_TRANSFORM_4, RO_COUNTER_TRASPIE, RO_GHOST_REFLECT, CHANGESHAPE_TRANSFORM_5, ICE_ELEMENTALDESTROY, DORMANT_USER, NEWBIE_USER, THIRTEENTH_BUFF, ARENA_UNSEAL_A, ARENA_UNSEAL_B, ARENA_UNSEAL_C, ARENA_UNSEAL_D, ARENA_UNSEAL_E, IN_BATTLE_RHAPSODY, IN_A_DECAL, IN_B_DECAL, CHANGESHAPE_TRANSFORM_6, CHANGESHAPE_TRANSFORM_7, SPIRIT_KING_WIND_AVE_B, EARTH_KING_BARRIER1_AVE, EARTH_KING_BARRIER2_AVE, FOCUS_SHIELD, RAISE_SHIELD, TRUE_VANGUARD, SHIELD_WALL, FOOT_TRAIL, LEGEND_DECO_HERO, CHANGESHAPE_TRANSFORM_8, SPIRIT_KING_WIND_AVE, U098_BUFF_TA_DECO, ORFEN_ENERGY1_AVE, ORFEN_ENERGY2_AVE, ORFEN_ENERGY3_AVE, ORFEN_ENERGY4_AVE, ORFEN_ENERGY5_AVE, UNHOLY_BARRIER_AVE, RUDOLF_A_AVE, RUDOLF_B_AVE, RUDOLF_C_AVE, OLYMPIAD_MEDAL_AVE, OLYMPIAD_SPORT_A_AVE, OLYMPIAD_SPORT_B_AVE, OLYMPIAD_SPORT_C_AVE, D_CHAOS_MATCH_DECO_SMALL, TRANS_DECO_R, TRANS_DECO_B, TRANS_DECO_Y, TRANS_DECO_G, TRANS_DECO_P, TRANS_DECO_P2, TRANS_DECO_W, TRANS_DECO_R2, TRANS_DECO_W2, HDDOWN_AVE, HDMDOWN_AVE, KISSNHEART_AVE, EARTH_BARRIER_AVE, LILITH_DARK_BARRIER_AVE, EARTH_BARRIER2_AVE, CROFFIN_QUEEN_INVINCIBILITY_AVE, MPDOWN_AVE, WORLDCUP_RED_AVE, WORLDCUP_BLUE_AVE, SURGEWAVE_AVE, BLESS_AVE, ANTHARAS_RAGE_AVE, G_BARRIER_AVE, FIREWORKS_001T, FIREWORKS_002T, FIREWORKS_003T, FIREWORKS_004T, FIREWORKS_005T, FIREWORKS_006T, FIREWORKS_007T, FIREWORKS_008T, FIREWORKS_009T, FIREWORKS_010T, FIREWORKS_011T, FIREWORKS_012T, FIREWORKS_013T, FIREWORKS_014T, FIREWORKS_015T, P_CAKE_AVE, ZARICHE_PRISION_AVE, RUDOLPH, XMAS_HEART_AVE, XMAS_HAND_AVE, LUCKYBAG_AVE, HEROIC_MIRACLE_AVE, POCKETPIG_AVE, BLACK_STANCE_AVE, BLACK_TRANS_DECO_AVE, KAMAEL_BLACK_TRANSFORM, WHITE_STANCE_AVE, HEAL_DECO_AVE, KAMAEL_WHITE_TRANSFORM, LONG_RAPIER_WHITE_AVE, LONG_RAPIER_BLACK_AVE, ZARICHE_PRISION2_AVE, BLUEHEART_AVE, ATTACK_BUFF_AVE, SHIELD_BUFF_AVE, BERSERKER_BUFF_AVE, DRAGON_ULTIMATE, CHANGE_HALLOWEEN, BR_Y_1_ACCESSORY_R_RING, BR_Y_1_ACCESSORY_EARRING, BR_Y_1_ACCESSORY_NECKRACE, BR_Y_2_ACCESSORY_R_RING, BR_Y_2_ACCESSORY_EARRING, BR_Y_2_ACCESSORY_NECKRACE, BR_Y_3_ACCESSORY_R_RING, BR_Y_3_ACCESSORY_EARRING, BR_Y_3_ACCESSORY_NECKRACE, BR_TALI_DECO, BASEBALL_UNIFORM, SANTA_CLAUS_LIGHT, SANTA_CLAUS_BLACK, SANTA_CLAUS_RED, SCHOOL_UNIFORM_LIGHT, SCHOOL_UNIFORM_BLACK, SCHOOL_UNIFORM_RED, BEACH_SWIMSUIT_LIGHT, BEACH_SWIMSUIT_BLACK, BEACH_SWIMSUIT_RED, TEDDY_BEAR_LIGHT, TEDDY_BEAR_BLACK, TEDDY_BEAR_RED, TOY_CAT_LIGHT, TOY_CAT_BLACK, TOY_CAT_RED, TOY_PANDA_LIGHT, TOY_PANDA_BLACK, TOY_PANDA_RED, BASEBALL_UNIFORM_LIGHT, BASEBALL_UNIFORM_BLACK, BASEBALL_UNIFORM_RED, SEDUCTIVE_LIGHT, SEDUCTIVE_BLACK, SEDUCTIVE_RED, BLACK_SCHOOL_UNIFORM_LIGHT, BLACK_SCHOOL_UNIFORM_BLACK, BLACK_SCHOOL_UNIFORM_RED, HANBOK_LIGHT, HANBOK_BLACK, HANBOK_RED, METAL_SUIT_LIGHT, METAL_SUIT_BLACK, METAL_SUIT_RED, SAMURAI_LIGHT, SAMURAI_BLACK, SAMURAI_RED, GREEN_ARCHER_LIGHT, GREEN_ARCHER_BLACK, GREEN_ARCHER_RED, FORMAL_WEAR_LIGHT, FORMAL_WEAR_BLACK, FORMAL_WEAR_RED, KAT_THE_CAT_LIGHT, KAT_THE_CAT_BLACK, KAT_THE_CAT_RED, HALLOWEEN_LIGHT, HALLOWEEN_BLACK, HALLOWEEN_RED, ALLURING_SWIMSUIT_LIGHT, ALLURING_SWIMSUIT_BLACK, ALLURING_SWIMSUIT_RED, VAMPIRE_LIGHT, VAMPIRE_BLACK, VAMPIRE_RED, DARK_KNIGHT_LIGHT, DARK_KNIGHT_BLACK, DARK_KNIGHT_RED, CHEVALIER_LIGHT, CHEVALIER_BLACK, CHEVALIER_RED, RED_ARCHER_LIGHT, RED_ARCHER_BLACK, RED_ARCHER_RED, BLUE_PIRATE_LIGHT, BLUE_PIRATE_BLACK, BLUE_PIRATE_RED, DARK_RED_WIZARD_LIGHT, DARK_RED_WIZARD_BLACK, DARK_RED_WIZARD_RED, MYSTIC_LIGHT, MYSTIC_BLACK, MYSTIC_RED, BLACK_PIRATE_LIGHT, BLACK_PIRATE_BLACK, BLACK_PIRATE_RED, RED_NOBLESSE_LIGHT, RED_NOBLESSE_BLACK, RED_NOBLESSE_RED, BARBARIAN_WOLF_LIGHT, BARBARIAN_WOLF_BLACK, BARBARIAN_WOLF_RED, VALKYRIE_LIGHT, VALKYRIE_BLACK, VALKYRIE_RED, KELBIM_LIGHT, KELBIM_BLACK, KELBIM_RED, NINJA_LIGHT, NINJA_BLACK, NINJA_RED, HIGH_PRIEST_LIGHT, HIGH_PRIEST_BLACK, HIGH_PRIEST_RED, WHITE_NOBLESSE_LIGHT, WHITE_NOBLESSE_BLACK, WHITE_NOBLESSE_RED, PURPLE_COWBOY_LIGHT, PURPLE_COWBOY_BLACK, PURPLE_COWBOY_RED, BLUE_MUSKETEER_LIGHT, BLUE_MUSKETEER_BLACK, BLUE_MUSKETEER_RED, ZAKEN_LIGHT, ZAKEN_BLACK, ZAKEN_RED, DRAGON_LIGHT, DRAGON_BLACK, DRAGON_RED, ANAKIM_LIGHT, ANAKIM_BLACK, ANAKIM_RED, LILITH_LIGHT, LILITH_BLACK, LILITH_RED, FREYA_LIGHT, FREYA_BLACK, FREYA_RED, CUSTOM_ABNORMAL1, CUSTOM_ABNORMAL2, CUSTOM_ABNORMAL3, CUSTOM_ABNORMAL4, CUSTOM_ABNORMAL5, CUSTOM_ABNORMAL6, CUSTOM_ABNORMAL7, CUSTOM_ABNORMAL8, CUSTOM_ABNORMAL9, CUSTOM_ABNORMAL10, CUSTOM_ABNORMAL11, CUSTOM_ABNORMAL12, CUSTOM_ABNORMAL13, CUSTOM_ABNORMAL14, CUSTOM_ABNORMAL15, CUSTOM_ABNORMAL16, CUSTOM_ABNORMAL17, CUSTOM_ABNORMAL18, CUSTOM_ABNORMAL19, CUSTOM_ABNORMAL20, CUSTOM_ABNORMAL21, CUSTOM_ABNORMAL22, CUSTOM_ABNORMAL23, CUSTOM_ABNORMAL24, CUSTOM_ABNORMAL25, CUSTOM_ABNORMAL26, CUSTOM_ABNORMAL27, CUSTOM_ABNORMAL28, CUSTOM_ABNORMAL29, CUSTOM_ABNORMAL30, CUSTOM_ABNORMAL31, CUSTOM_ABNORMAL32, CUSTOM_ABNORMAL33, CUSTOM_ABNORMAL34, CUSTOM_ABNORMAL35, CUSTOM_ABNORMAL36, CUSTOM_ABNORMAL37, CUSTOM_ABNORMAL38, CUSTOM_ABNORMAL39, CUSTOM_ABNORMAL40};
    }

    static {
        c = AbnormalEffect.a();
        EMPTY_ARRAY = new AbnormalEffect[0];
    }
}
