/*
 * Decompiled with CFR 0.152.
 */
package l2.gameserver.network.l2.s2c;

import l2.gameserver.model.Player;
import l2.gameserver.model.base.Element;
import l2.gameserver.model.base.Experience;
import l2.gameserver.model.items.Inventory;
import l2.gameserver.model.pledge.Alliance;
import l2.gameserver.model.pledge.Clan;
import l2.gameserver.network.l2.s2c.L2GameServerPacket;
import l2.gameserver.utils.Location;

public class GMViewCharacterInfo
extends L2GameServerPacket {
    private Location _loc;
    private int[][] l;
    private int tG;
    private int fZ;
    private int gg;
    private int class_id;
    private int pvp_flag;
    private int karma;
    private int level;
    private int tq;
    private int yo;
    private int yp;
    private int yq;
    private int yr;
    private int ys;
    private int yt;
    private int _sp;
    private int curHp;
    private int maxHp;
    private int curMp;
    private int maxMp;
    private int curCp;
    private int maxCp;
    private int xT;
    private int xU;
    private int yv;
    private int ta;
    private int yw;
    private int yx;
    private int yy;
    private int yz;
    private int yA;
    private int yB;
    private int yD;
    private int yE;
    private int yF;
    private int tc;
    private int td;
    private int te;
    private int yG;
    private int clan_id;
    private int clan_crest_id;
    private int ally_id;
    private int yH;
    private int yI;
    private int yJ;
    private int tk;
    private int yK;
    private int yL;
    private int yM;
    private int sS;
    private int sT;
    private int sU;
    private int yN;
    private int running;
    private int yO;
    private int yP;
    private String _name;
    private String title;
    private long _exp;
    private double ac;
    private double ad;
    private double V;
    private double W;
    private Element c;
    private int of;
    private int og;
    private int oh;
    private int oi;
    private int oj;
    private int ok;
    private int ol;
    private int yQ;
    private int vitality;
    private int yR;
    private boolean eW;
    private double ae;

    public GMViewCharacterInfo(Player player) {
        this._loc = player.getLoc();
        this.tG = player.getObjectId();
        this._name = player.getName();
        this.fZ = player.getRace().ordinal();
        this.gg = player.getSex();
        this.class_id = player.getClassId().getId();
        this.level = player.getLevel();
        this._exp = player.getExp();
        this.yo = player.getSTR();
        this.yq = player.getDEX();
        this.yp = player.getCON();
        this.yr = player.getINT();
        this.ys = player.getWIT();
        this.yt = player.getMEN();
        this.curHp = (int)player.getCurrentHp();
        this.maxHp = player.getMaxHp();
        this.curMp = (int)player.getCurrentMp();
        this.maxMp = player.getMaxMp();
        this._sp = player.getIntSp();
        this.xT = player.getCurrentLoad();
        this.xU = player.getMaxLoad();
        this.yw = player.getPAtk(null);
        this.yx = player.getPAtkSpd();
        this.yy = player.getPDef(null);
        this.yz = player.getEvasionRate(null);
        this.yA = player.getAccuracy();
        this.yB = player.getCriticalHit(null, null);
        this.yD = player.getMAtk(null, null);
        this.yE = player.getMAtkSpd();
        this.yF = player.getMDef(null, null);
        this.pvp_flag = player.getPvpFlag();
        this.karma = player.getKarma();
        this.sS = player.getRunSpeed();
        this.sT = player.getWalkSpeed();
        this.sU = player.getSwimSpeed();
        this.ac = player.getMovementSpeedMultiplier();
        this.ad = player.getAttackSpeedMultiplier();
        this.tq = player.getMountType();
        this.V = player.getColRadius();
        this.W = player.getColHeight();
        this.tc = player.getHairStyle();
        this.td = player.getHairColor();
        this.te = player.getFace();
        this.yG = player.isGM() ? 1 : 0;
        this.title = player.getTitle();
        this.ae = Experience.getExpPercent(player.getLevel(), player.getExp());
        Clan clan = player.getClan();
        Alliance alliance = clan == null ? null : clan.getAlliance();
        this.clan_id = clan == null ? 0 : clan.getClanId();
        this.clan_crest_id = clan == null ? 0 : clan.getCrestId();
        this.ally_id = alliance == null ? 0 : alliance.getAllyId();
        this.tk = player.isInObserverMode() ? 7 : player.getPrivateStoreType();
        this.yN = Math.max(player.getSkillLevel(1320), 0);
        this.yL = player.getPkKills();
        this.yM = player.getPvpKills();
        this.yv = player.getGivableRec();
        this.ta = player.getReceivedRec();
        this.curCp = (int)player.getCurrentCp();
        this.maxCp = player.getMaxCp();
        this.running = player.isRunning() ? 1 : 0;
        this.yO = player.getPledgeClass();
        this.yI = player.isNoble() ? 1 : 0;
        this.yJ = player.isHero() ? 1 : 0;
        this.yK = player.getNameColor();
        this.yH = player.getTitleColor();
        this.c = player.getAttackElement();
        this.of = player.getAttack(this.c);
        this.og = player.getDefence(Element.FIRE);
        this.oh = player.getDefence(Element.WATER);
        this.oi = player.getDefence(Element.WIND);
        this.oj = player.getDefence(Element.EARTH);
        this.ok = player.getDefence(Element.HOLY);
        this.ol = player.getDefence(Element.UNHOLY);
        this.vitality = (int)player.getVitality();
        this.yR = player.getTalismanCount();
        this.yP = player.getRaidBossPoints();
        this.l = new int[59][3];
        for (int n : Inventory.PAPERDOLL_ORDER) {
            this.l[n][0] = player.getInventory().getPaperdollObjectId(n);
            this.l[n][1] = player.getInventory().getPaperdollItemId(n);
            this.l[n][2] = player.getInventory().getPaperdollAugmentationId(n);
        }
    }

    @Override
    protected final void writeImpl() {
        this.writeC(149);
        this.writeD(this._loc.x);
        this.writeD(this._loc.y);
        this.writeD(this._loc.z);
        this.writeD(this._loc.h);
        this.writeD(this.tG);
        this.writeS(this._name);
        this.writeD(this.fZ);
        this.writeD(this.gg);
        this.writeD(this.class_id);
        this.writeD(this.level);
        this.writeQ(this._exp);
        this.writeF(this.ae);
        this.writeD(this.yo);
        this.writeD(this.yq);
        this.writeD(this.yp);
        this.writeD(this.yr);
        this.writeD(this.ys);
        this.writeD(this.yt);
        this.writeD(0);
        this.writeD(0);
        this.writeD(this.maxHp);
        this.writeD(this.curHp);
        this.writeD(this.maxMp);
        this.writeD(this.curMp);
        this.writeQ(this._sp);
        this.writeD(this.xT);
        this.writeD(this.xU);
        this.writeD(this.yL);
        for (int n : Inventory.PAPERDOLL_ORDER) {
            this.writeD(this.l[n][0]);
        }
        for (int n : Inventory.PAPERDOLL_ORDER) {
            this.writeD(this.l[n][1]);
        }
        for (int i = 0; i < 11; ++i) {
            this.writeD(0);
            this.writeD(0);
        }
        this.writeC(this.yR);
        this.writeC(this.eW ? 1 : 0);
        this.writeD(0);
        this.writeH(0);
        this.writeD(this.yw);
        this.writeD(this.yx);
        this.writeD(this.yy);
        this.writeD(this.yz);
        this.writeD(this.yA);
        this.writeD(this.yB);
        this.writeD(this.yD);
        this.writeD(this.yE);
        this.writeD(this.yx);
        this.writeD(this.yF);
        this.writeD(0);
        this.writeD(0);
        this.writeD(0);
        this.writeD(this.pvp_flag);
        this.writeD(this.karma);
        this.writeD(this.sS);
        this.writeD(this.sT);
        this.writeD(this.sU);
        this.writeD(this.sU);
        this.writeD(this.sS);
        this.writeD(this.sT);
        this.writeD(this.sS);
        this.writeD(this.sT);
        this.writeF(this.ac);
        this.writeF(this.ad);
        this.writeF(this.V);
        this.writeF(this.W);
        this.writeD(this.tc);
        this.writeD(this.td);
        this.writeD(this.te);
        this.writeD(this.yG);
        this.writeS(this.title);
        this.writeD(this.clan_id);
        this.writeD(this.clan_crest_id);
        this.writeD(this.ally_id);
        this.writeC(this.tq);
        this.writeC(this.tk);
        this.writeC(this.yN);
        this.writeD(this.yL);
        this.writeD(this.yM);
        this.writeH(this.yv);
        this.writeH(this.ta);
        this.writeD(this.class_id);
        this.writeD(0);
        this.writeD(this.maxCp);
        this.writeD(this.curCp);
        this.writeC(this.running);
        this.writeC(321);
        this.writeD(this.yO);
        this.writeC(this.yI);
        this.writeC(this.yJ);
        this.writeD(this.yK);
        this.writeD(this.yH);
        this.writeH(this.c.getId());
        this.writeH(this.of);
        this.writeH(this.og);
        this.writeH(this.oh);
        this.writeH(this.oi);
        this.writeH(this.oj);
        this.writeH(this.ok);
        this.writeH(this.ol);
        this.writeD(this.yP);
        this.writeD(this.vitality);
    }
}
